CLUSTAL multiple sequence alignment by MUSCLE (3.8)


XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
PWZ36664.1                ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
sp|Q9LKR8|RAF1_ARATH      ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
KAG5072050.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              --------------------------------------------------MSRWPAEHVI
KJB80888.1                MLLWMLIQLMIGPHYFVLTLPPLVLTFCWARVYVAHGPFRLWADSAPTGHMSRWPAEHVI
XP_012463925.1            ------------------------------------------------------------
XP_007030468.2            ------------------------------------------------------------
EOY10970.1                ------------------------------------------------------------
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ------------------------------------------------------------
KAG5152164.1              ------------------------------------------------------------
KAG4997621.1              ------------------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              ------------------------------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
PWZ36664.1                ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
sp|Q9LKR8|RAF1_ARATH      ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
KAG5072050.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              LSASSLDVCESRSWPSLSSCKLDLRPYLASWVLGSALRDGSASLLCCPLVIRQTLQASKL
KJB80888.1                LSASSLDVCESRSWPSLSSCKLDLRPYLASWVLGSALRDGSASLLCCPLVIRQTLQASKL
XP_012463925.1            ------------------------------------------------------------
XP_007030468.2            ------------------------------------------------------------
EOY10970.1                -------------MGPCTITTVLVGLLSFLNKAQREPIHFSCQIRQPWKALPGLPSPSFL
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ------------------------------------------------------------
KAG5152164.1              ------------------------------------------------------------
KAG4997621.1              ------------------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              ------------------------------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            -----------MLSLSHPHPASTGP---------RH--RKPLSTAPQRRRRFSYNIAALI
XP_044969817.1            -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRCTYTIAALI
BAJ84883.1                -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRCTYTIAALI
XP_044449078.1            -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRYTYTIAALI
XP_044322972.1            -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRCTYTIAALI
XP_044395281.1            -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRCTYTIAALI
KAF6988857.1              -----------MLSVSHPHPAASTGP--------RH--RKPLSTAHHRRRRYTYTIAALI
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ---------MLSLSHPHPHPASTTAAAAARHHHRRN--APFAPHHRRRRRFAHLTTSAVI
KAB8112826.1              ---------MLSLSHPHPHPASTTAAAAARHHHRRN--APFAPHHRRRRRFAHLTTSAVI
XP_004982996.1            ---------MLSLSHPHTHPAAAPRH----QRAPRP--AVAATPASCRRRASHIAASAIL
XP_002448784.1            -----------MLSLSHPHPAASTTA----PRHQRT--PRAATPVWRRRRASHIVASAIL
NP_001140763.1            ---------MLSLSHPHPHPAASTTA--------PR--HQRTAPVWHRRRASHIAASAIL
PWZ36664.1                ------------------------------------------------------------
XP_016488923.1            ---------MFSLTVNSPKPLSLSTP-----FLPTH--PHPLPSITHKPNLNPKPITALI
XP_016475347.1            ---------MFSLTVNSPKPLSLSTP-----FLPSH--HHPLPSITHKPILNPKPITALI
XP_004249913.1            ---------MFSLTVNSPKSLSLSTP-----FLPSH--PHPIPTITHKPNLSPRPISALI
KAH0714466.1              ---------MFSLTVNSPKPLSLSTP-----FLPSH--PHPLPTITHKPNLTPRPISALI
KAH0711684.1              ---------MFSLTVNSPKPLSLSTP-----FLPSH--PHSLPTITHKPNLTPRPISALI
XP_006350959.1            ---------MFSLTVNSPKPLSLSTP-----FLPSH--PHPLPTITHKPNLTPRPISALI
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ---------MFSLKSSISSPFTQST---------TH--GLFTNPITRPVNPLPRTVTASM
sp|Q9LKR8|RAF1_ARATH      ---------MLSLTATTLSSSIFTQS---------K--THGFFNTRPVYRKPFTTITSAL
XP_020878074.1            ---------MLSLTATTLKSSLFTQSK-----------THGFSNTRPVYPKPFTTITAAL
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ----------------------------------------------MGKGYIKRLLDCWV
KAG5072050.1              -----------MGRVET---------------------EFYYMKTLGLQPACFKPLTH--
KAH1203488.1              --------------------------------------MSIYHFPHHDR-----------
KAH1203487.1              --------------------------------------MSIYHFPHHDR-----------
CAN61036.1                -----------MLSLNAAASLSLSH---------HH--LLHRRHHHHRLKTHVKPISATI
XP_002268548.1            -----------MLSLNAPASLSLSH---------HH--LLHRRHHHHRLKTHVKPISATI
RVW88115.1                -----------MLSLNAAASLSLSH---------HH--LLHRRHHHHRLKTHVKPISATI
XP_011465980.1            ---------MLSLTSSTLKPTFSPFT----STTTFL--NPHQPPRLLHPKPSLKPISASI
MBA0602665.1              TSIPLCKYSTFINSLTMLSSTSLNPITNPKIPFFSS--FSIQNPSLLSFHLPFSPSKTLL
KJB80888.1                TSIPLCKYSTFINSLTMLSSTSLNPITNPKIPFFSS--FSIQNPSLLSFHLPFSPSKTLL
XP_012463925.1            ----------------MLSSTSLNPITNPKIPFFSS--FSIQNPSLLSFHLPFSPSKTLL
XP_007030468.2            -----------MLSSTSLKPITNPKNLVFSSFLNQNPSLFSFHPSFPLSKTLLKPISATL
EOY10970.1                LIFCLSIFFLTMLSSTSLKPITNPKNLVFSSFLNQNPSLFSFHPSFPLSKTLLKPISATL
XP_021888657.1            ---------MLSVTTNTFKLIISSPIHSTTNFLTTH--QPPSP----NLKPSLRPISATL
XP_002319651.1            ---------MLSPTLNTHKPLFLSSSNNKPFSSPFL--SQQPLFILHLSKTPFKPTKTLS
XP_002521962.1            ---------MLSATVNTHIPISLSNPNKPFSSSFIT--PLFTYVSPSSQKTQLKPISAAL
XP_021624035.1            ---------MFSATVNSLIPISLSNSSKPFSSSFLSPCLPLFIFQSPFSKTTVKPISATL
XP_004142574.1            ---------MLSSTITNANSLSSLSSIAHTTSIFLH--QPRDSPLRLFLRRRLNPISAII
XP_004495565.1            ---------MLSLS---PCITSVNTPNLKFPNNNGN--FFLLPSPSSNHHRPLKPISAII
XP_003590938.1            ---------MLSPCISSVNTLNLKF---------LN--IPPSSSNLNRSFYRFKSISAVL
AFK41237.1                ---------MLSPCISSVNTLNLKFLN-----------IPPSSSNLNRSFYRFKSISAVL
AGV54807.1                -------MQTLTNMLSLSPSVTANTHTLKPSNPNHL--FLITSPSFTNRRHSVKPISAII
XP_007144004.1            -------MQTLTNMLSLSPSVTANTHTLKPSNPNHL--FLITSPSFTNRRHSVKPISAII
XP_025980010.1            ------------------------------------------MSNQKSTESCIKNLEVQV
KAG5004370.1              ------------MRRNHSNSGNYRNPCLTMHQPWAS--LLVYGIKRVEGRSWPAPITGRL
KAG5152164.1              ------------MRRNHSNSGNYRNPCLTMHQPWAS--LLVYGIKRVEGRSWPAPITGRL
KAG4997621.1              ------------MRRNHSNSGNYRNPCLTMHQPWAS--LLVYGIKRVEGRSWPAPITGRL
XP_003536143.1            ---------MLSLSVPPLNLKPITPN--------DL--FLSSASPSPHRRYFVKPISAVL
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ---------MSSSSIS----------------------VIQLSFSAQTKSLRYVGIFFFL
KAG5075806.1              ------------MRRNHSNSGNYRNPCLTMHQPWAS--LLVYGIKRVEGRSWPAPITGRL
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              --------MWLDLSDNALEVISSTFGNLSLEYLDLS--LIKFEGSTFREFGAFKSLKTLN
KAG4996767.1              --------MWLDLSDNALEVISSTFGNLSLEYLDLS--LIKFEGSTFPEFGAFKSLKTLN
                                                                                      

XP_003573987.1            LPGGGGGRGSPPNGGKLILPG--GGGGGVGGGGSSGMLPRTPPPSSPG--QLYQPYHPPP
XP_044969817.1            LPGGGGPRGSPPNGGKLILPGS-GGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP
BAJ84883.1                LPGGGGPRGSPPNGGKLILPGS-GGGGGRGGGVGGGMLPRTPPPTAPPG-QLYQPFHPPP
XP_044449078.1            LPGGGGPRGSPPNGGKLILPGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP
XP_044322972.1            LPGGGGPRGSPPNGGKLILPGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP
XP_044395281.1            LPGGGGPRGSPPNGGKLILPGS-GGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP
KAF6988857.1              LPGGGGPRGSPPNGGKLILPGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            LGP---------------------DGRPIGGGPRDNKLPFTPPPTAPPD-QLYQPFHPPP
KAB8112826.1              LGP---------------------DGRPIGGGPRDNKLPFTPPPTAPPD-QLYQPFHPPP
XP_004982996.1            LPG-----------------------GGSTGGRGDRKLPFTPPPMAPPG-QLYQPFHPPP
XP_002448784.1            LPG--------------------GGSTGGGGGPGDRRLPFTPPPMAPPG-QLYQPFHPPP
NP_001140763.1            LPG--------------------GGSTGGRGGPGDRRLPFTPPPMAPPG-QLYQPFHPPP
PWZ36664.1                --------------------------------------------MAPPG-QLYQPFHPPP
XP_016488923.1            IPP----------------------------SSGQQQQYSTQQQQQQ---QLYQPFRPPP
XP_016475347.1            IPP----------------------------SSGQQQQYSTQQQ------QLYQPFRPPP
XP_004249913.1            IPP----------------------------SGQRNQQYSTAPPQQQ---QLYQPFRPPP
KAH0714466.1              IPP----------------------------SGQRNQQYSTEPPQQQ---QLYQPFRPPP
KAH0711684.1              IPP----------------------------SGQRNQQYSTAAPQQQ---QLYQPFRPPP
XP_006350959.1            IPP----------------------------SGQRNQQYSTAAPQQQ---QLYQPFRPPP
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            IPK----------------------------KSSANMIPRNPPARQ----QLYQPFRPPS
sp|Q9LKR8|RAF1_ARATH      IPA----------------------------------SNRQAPPKQ----QLYQPFRPPP
XP_020878074.1            IPA----------------------------------SNRQAPPQQ----QLYQPFRPPP
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              IHV---------------------------------------------------------
KAG5072050.1              --------------------------------------------------SLTHVYHFPH
KAH1203488.1              -----------------------------------------------------VPRLPPH
KAH1203487.1              -----------------------------------------------------VPRLPPH
CAN61036.1                IPS-----------------------------------SSTPRHSQQP--ELYQPFRPPS
XP_002268548.1            IPS-----------------------------------SSTPRHSQQP--ELYQPFRPPS
RVW88115.1                IPS-----------------------------------SSTPRHSQQP--ELYQPFRPPS
XP_011465980.1            QHL-----------------------------------PSHPKPNQ----QVYQPFRPPP
MBA0602665.1              KPI------------------------------SATLIPSTPPPQQQ---QLYQPFRPPP
KJB80888.1                KPI------------------------------SATLIPSTPPPQQQ---QLYQPFRPPP
XP_012463925.1            KPI------------------------------SATLIPSTPPPQQQ---QLYQPFRPPP
XP_007030468.2            IPS-------------------------------------NPQPQQQ---QLYQPFRPPP
EOY10970.1                IPS-------------------------------------NPQPQQQ---QLYQPFRPPP
XP_021888657.1            IPA--------------------------------------PTPPSNQQQQLYQPFRPPP
XP_002319651.1            VSA--------------------------------TRIPSSPPPYQ----QLYQPFRPPP
XP_002521962.1            IPS-------------------------------------TPPPSNQ---QLYQPFRPPP
XP_021624035.1            IPA-------------------------------------SPSPSNQ---QLYQPFRPPP
XP_004142574.1            NPS-----------------------------------SSSLAAKQ----QVYQPFRPPP
XP_004495565.1            NPS-------------------------SSPRQKQQQRQQQQQQQQQPQRQLYQPFRPPP
XP_003590938.1            NNP---------------------------SSHSKKQRQVQQQQQQQPQKQLYQPFRPPP
AFK41237.1                NSP---------------------------SSHSKKQRQVQQQQQQQPQKQLYQPFRPPP
AGV54807.1                NPS------------------------------------SFKNPQPPPQQQVYQPFRPPP
XP_007144004.1            NPS------------------------------------SFKNPQPPPQQQVYQPFRPPP
XP_025980010.1            G-------------------------------------------------QLAKQLEDRP
KAG5004370.1              WIH----------------------------AASKVPEESTIKAMEYFYKEIYALNGITD
KAG5152164.1              WIH----------------------------AASKVPEESTIKAMEYFYKEIYALNGITD
KAG4997621.1              WIH----------------------------AASKVPEESTIKAMEYFYKEIYALNGITD
XP_003536143.1            NSS---------------------------------SFKKPEQPLLPQH-QVYQPFRPPP
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              LGL---------------------------------------------------------
KAG5075806.1              WIH----------------------------SASKVPEESTIKAMEYFYKEIYALNGISD
KAG4919720.1              --------------------------------------------------MISRRF----
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              LSN-----------------------------------------------NMLV------
KAG4996767.1              LSN-----------------------------------------------NMLV------
                                                                                      

XP_003573987.1            --SPLPDTFRNLDL---------------------------TERLAVL----RDRMGRW-
XP_044969817.1            --SPLPENYRNLDL---------------------------TERLAVL----RDRMGRW-
BAJ84883.1                --SPLPENYRNLDL---------------------------TERLAVL----RDRMGRW-
XP_044449078.1            --NPLPETYRNLDL---------------------------TERLAVL----RDRMGRW-
XP_044322972.1            --NPLPETYRNLDL---------------------------TERLAVL----RDRMGRW-
XP_044395281.1            --NPLPENYRNLDL---------------------------TERLAVL----RDRMGRW-
KAF6988857.1              --NPLPETYRNLDL---------------------------TERLAVL----RDRMGRW-
EAY78710.1                ------------------------------------------------------MISTW-
XP_015614647.1            --SPLPDKYKDLDL---------------------------GQRLAVL----RDRLGLW-
KAB8112826.1              --SPLPDKYKDLDL---------------------------GQRLAVL----RDRLGLW-
XP_004982996.1            --SPLPSKFRTLDL---------------------------TQRLEVL----RERLGQW-
XP_002448784.1            --SPLPPSLRNLDL---------------------------TQRLQIL----RDRMGLW-
NP_001140763.1            --SPLPPSLRNLDL---------------------------SERLQIL----RDRMGLW-
PWZ36664.1                --SPLPPSLRNLDL---------------------------SERLQIL----RDRMGLW-
XP_016488923.1            --PLLPPKFRNLDT---------------------------NSKLEVL----ANRLGLW-
XP_016475347.1            --PPLPPKFRNLDT---------------------------NAKLEVL----SNRLGLW-
XP_004249913.1            --SPLPPKFRNLDT---------------------------NSKLEVL----ANRLGLW-
KAH0714466.1              --SPLPPKFRNLDT---------------------------NSKLEVL----ANRLGLW-
KAH0711684.1              --SPLPPKFRNLDT---------------------------NSKLEVL----ANRLGLW-
XP_006350959.1            --SPLPPKFRHLDT---------------------------NSKLEVL----ANRLGLW-
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            --SPIPTKFRSLDS---------------------------AGKIEIL----AGRMALW-
sp|Q9LKR8|RAF1_ARATH      --SPIPPKFRSLDT---------------------------AGKIEVL----ADRLGLW-
XP_020878074.1            --SPIPPKFRSLDT---------------------------AGRIEVL----ADRLGLW-
KAG5031773.1              ----------MVVL---------------------------ASRINIL----ANRLDLW-
KAG5045990.1              ------------------------------------------GRINIL----ANRLDLW-
KAG5072050.1              HGRVLPPLFSLLTF---------------------------H------------------
KAH1203488.1              --IPRPPLFSLLTF---------------------------H------------------
KAH1203487.1              --IPRPPLFSLLTF---------------------------HG-----------------
CAN61036.1                PNAPIPSHFRSLDT---------------------------GSRLEVL----SNRLGLW-
XP_002268548.1            PNAPIPSHFRSLDT---------------------------GSRLEVL----SNRLGLW-
RVW88115.1                PNAPIPSHFRSLDT---------------------------GSRLEVL----SNRLGLW-
XP_011465980.1            --SPIPEQYSSLDV---------------------------NGRLEIL----ANRLGLW-
MBA0602665.1              --SPLPPKFRSLDA---------------------------QGRLDVL----ANRNGLW-
KJB80888.1                --SPLPPKFRSLDA---------------------------QGRLDVL----ANRNGLW-
XP_012463925.1            --SPLPPKFRSLDA---------------------------QGRLDVL----ANRNGLW-
XP_007030468.2            --SPLPSQFRSLDV---------------------------AARLEVL----ANRGGLW-
EOY10970.1                --SPLPSQFRSLDV---------------------------AARLEVL----ANRGGLW-
XP_021888657.1            --SPVPSQFKSLDA---------------------------AGRLDVL----ASRLGLW-
XP_002319651.1            --SPIPSQYKSLDA---------------------------PSRLEIL----SNRLGLW-
XP_002521962.1            --SPIPSQFSSLDT---------------------------AGRLEVL----ANRLGLW-
XP_021624035.1            --SPIPSQYGSLDT---------------------------ASRLDIL----TNRLGLW-
XP_004142574.1            --SPLPPQYRSLDT---------------------------EGKLNIL----SNRLGLW-
XP_004495565.1            --TSLPPKYGDLDI---------------------------PARLEIL----ANRLGVW-
XP_003590938.1            --TPLPSKYDNLDI---------------------------PGRIDIL----ANRLGAW-
AFK41237.1                --TPLPSKYDNLDI---------------------------PGRIDIL----ANRLGAW-
AGV54807.1                --EPLPSQYSTLDI---------------------------AGRIDIL----ANRLGLW-
XP_007144004.1            --EPLPSQYSTLDI---------------------------AGRIDIL----ANRLGLW-
XP_025980010.1            ----------------------------------------------------SSSFGAN-
KAG5004370.1              --IQFPQHYPVSRL---------------------------LGCVEVVGCLTRDELACW-
KAG5152164.1              --IQFPQHYPVSRLLGIIPQPRSLLNVNSVQFIAHQFECLITGCVEVVGCLTRDELACW-
KAG4997621.1              --IQFPQHYPVSRL---------------------------LGCVEVVGCLTRDELACW-
XP_003536143.1            --SPLPSQFGTLDI---------------------------AGRIDIL----ANRLGLW-
KAH1191965.1              --------MGTLDI---------------------------AGRIDVL----ANRLALW-
KAG4908494.1              --PSASLLSGTLDI---------------------------AGRIDVL----ANRLALW-
KAG5075806.1              --IQFPQHYPVSRL---------------------------LGCVEVVGCLTRDELACW-
KAG4919720.1              ----------------------------------------------------DDK-----
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              --GEVPKELQGLEN---------------------------LQDFQIF----NNHLNAST
KAG4996767.1              --GEVPKELQGLEN---------------------------LQDFQIF----NNHLNAST
                                                                                      

XP_003573987.1            ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
XP_044969817.1            ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
BAJ84883.1                ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
XP_044449078.1            ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
XP_044322972.1            ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
XP_044395281.1            ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
KAF6988857.1              ----------YEYAPLISSLSREGFT-----------PASIEEATGMSGVEQNRLVVA--
EAY78710.1                ----------HEYAPLISALSREGFT-----------PSSIEEATGISGVEQNRVVVA--
XP_015614647.1            ----------HEYAPLISALSREGFT-----------PSSIEEATGISGVEQNSVVVA--
KAB8112826.1              ----------HEYAPLISALSREGFT-----------PSSIEEATGISGVEQNRVVVA--
XP_004982996.1            ----------HEYAPLISALSRDGFT-----------PSSIEEATSITGVEQNCLVVA--
XP_002448784.1            ----------HEYAPLIASLSRDGFN-----------PSSIQEATGISGVEQNSLVVA--
NP_001140763.1            ----------HEYAPLISSLSRDGFN-----------PSSIQEATGISGVEQNCLVVA--
PWZ36664.1                ----------HEYAPLISSLSRDGFN-----------PSSIQEATGISGVEQNCLVVA--
XP_016488923.1            ----------YEYAPLIPSLTREGFT-----------PSTLEEITGLTGVDQNRLVVA--
XP_016475347.1            ----------YEYAPLIPYLTSEGFT-----------PSTLEEITGLTGVEQNRLVVA--
XP_004249913.1            ----------YEYAPLIPSLTSEGFT-----------PSTLEEITGITGVEQNRLVVA--
KAH0714466.1              ----------YEYAPLIPSLTSEGFT-----------PSTLEEITGITGVEQNRLVVA--
KAH0711684.1              ----------YEYAPLIPSLTSEGFT-----------PSTLEEITGITGVEQNRLVVA--
XP_006350959.1            ----------YEYAPLIPSLTSEGFT-----------PSTLEEITGITGVEQNRLVVA--
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ----------FEYAPLISSLYTNGFT-----------PPTIEELTGISSIEQNRLIVG--
sp|Q9LKR8|RAF1_ARATH      ----------FEYAPLISSLYTEGFT-----------PPSIEELTGISGVEQNSLIVG--
XP_020878074.1            ----------FEYAPLISSLYTEGFI-----------PPSIEELTGLSGVEQNRLIVG--
KAG5031773.1              ----------YEYASLISSLIREGFS-----------PSTIEETTDISSIDQNRLIVG--
KAG5045990.1              ----------YEYASLSSSLIREGFS-----------PSTIEETTDISSIDQNRLIVG--
KAG5072050.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
CAN61036.1                ----------FEYAPLVSTLMQEGFT-----------PSSLEEATGISGVEQNRLVVA--
XP_002268548.1            ----------FEYAPLVSTLMQEGFT-----------PSSLEEATGISGVEQNRLVVA--
RVW88115.1                ----------FEYAPLVSTLMQEGFT-----------PSSLEEATGISGVEQNRLVVA--
XP_011465980.1            ----------YEYAPLIPSLLQQGFT-----------PPTIEEITGISGVEQNRLVVA--
MBA0602665.1              ----------FEYAPLIPSLYQEGFS-----------PPSIEEITGITGVEQNRLIVA--
KJB80888.1                ----------FEYAPLIPSLYQEGFS-----------PPSIEEITGITGVEQNRLIVA--
XP_012463925.1            ----------FEYAPLIPSLYQEGFS-----------PPSIEEITGITGVEQNRLIVA--
XP_007030468.2            ----------FEYAPLIPSLYQEGFS-----------PPSVEETTGISGVEQNRLIVA--
EOY10970.1                ----------FEYAPLIPSLYQEGFS-----------PPSVEETTGISGVEQNRLIVA--
XP_021888657.1            ----------FEYAPLIPSLYQEGFA-----------SPSIEEYTGISGVEQNRLVVA--
XP_002319651.1            ----------YEYAPLIPSLFQEGFT-----------PPSIEEATGISGVEQNRLVVG--
XP_002521962.1            ----------YEYAPLIPSLIQEGFS-----------PPSIEESTGISGVEQNRLVVA--
XP_021624035.1            ----------YEYALLIPSLIQEGFT-----------PPSIEESTGIPGVEQNRLVVA--
XP_004142574.1            ----------FEYAPLISSLLQEGFT-----------PPVLEEITGISGVQQNSFIVG--
XP_004495565.1            ----------HEYAPLITSLIREGFT-----------PPTIEETTGITGVEQNRIIVA--
XP_003590938.1            ----------HEYAPLITSLLREGFS-----------PPTLEETTGITGVEQNRIIVA--
AFK41237.1                ----------HEYAPLITSLLREGFS-----------PPTLEETTGITGVEQNRIIVA--
AGV54807.1                ----------YQYAPLITSLIREGFS-----------PPTIEETTGITGVEQNRLIVA--
XP_007144004.1            ----------YQYAPLITSLIREGFS-----------PPTIEETTGITGVEQNRLIVA--
XP_025980010.1            ----------IEKNP----------------------------------KEESKAIMT--
KAG5004370.1              ----------EMVPEGVRVEAQTDYCWLCERPQKLLIPFEMRGYQGVYNLEKK--IYE--
KAG5152164.1              ----------EMVPEGVRVEAQTDYCWLCERPQKLLIPFEMRGYQGVYNLEKK--IYE--
KAG4997621.1              ----------EMVPEGVRVEAQTDYCWLCERPQKLLIPFEMRGYQGVYNLEKK--IYE--
XP_003536143.1            ----------YEYAPLINSLIREGFS-----------PPTIEETTGISGVEQNRLIVG--
KAH1191965.1              ----------YEYAPLIASLIREGFS-----------PPTIEETTGISGVEQNRLIVG--
KAG4908494.1              ----------YEYAPLIASLIREGFS-----------PPTIEETTGISGVEQNRLIVG--
KAG5075806.1              ----------EMVPEGVRLEAQTDYCWLCEWPQKLLIPFEMRGYQGVYNLEKK--IYE--
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              SGSRHCGESDFPLTPWSQTGVHDKNS-----------NSSMEDSDAHKCMLRSHHASDEE
KAG4996767.1              SGSRHCGESDFPLTPWSQTGVHDKNS-----------NSSMEDSDAHKCMLRSHHASDEE
                                                                                      

XP_003573987.1            -SQVRDSLI-SD-EFP-----ADLIHYFDSYGG--PDLLYELR-----------------
XP_044969817.1            -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
BAJ84883.1                -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
XP_044449078.1            -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
XP_044322972.1            -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
XP_044395281.1            -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
KAF6988857.1              -SQVRDSLI-SD-DFP-----DDLLHYFDSYGG--PDLLYELR-----------------
EAY78710.1                -TQVRDSLV-AD-EGGFP---AELLRYFDSYGG--PELLYELR-----------------
XP_015614647.1            -TQVRDSLVADEGGFP-----AELLRYFDSYGG--PELLYELR-----------------
KAB8112826.1              -TQVRDSLVADEGGFP-----AELLRYFDSYGG--PELLYELR-----------------
XP_004982996.1            -SQVRDSLL-SE-TAA---FPPDLLPYFDSYGG--PDLLYELR-----------------
XP_002448784.1            -SQVRDSLL-DD-KVA--AFPPDLLPYFDSYGG--PDLLYELR-----------------
NP_001140763.1            -SQVRDSLL-DD-RAA--AFPPDLLPYFDSLGG--PEVLYELR-----------------
PWZ36664.1                -SQVRDSLL-DD-RAA--AFPPDLLPYFDSLGG--PEVLYELR-----------------
XP_016488923.1            -AQVRDSLVESA-ALD-----EETLSYFES-GG--AELLYEIR-----------------
XP_016475347.1            -AQVRDTLVESA-ALD-----EETLSYFES-GG--AELLYEIR-----------------
XP_004249913.1            -AQVRETLV-EC-GLD-----EETLSFFES-GG--AELLYEIR-----------------
KAH0714466.1              -AQVLDTLV-EC-GLD-----EETLSFFES-GG--AELLYEIR-----------------
KAH0711684.1              -AQVRDTLI-EC-GLD-----EETLSFFES-GG--AELLYEIR-----------------
XP_006350959.1            -AQVRDTLV-EC-GLD-----EETLSFFES-GG--AELLYEIR-----------------
EFH61612.1                -----------------------------------MSYRYNLA-----------------
XP_002882362.1            -AQVRDSIL-QS-IHE-----PELIAAFDT-GG--AELLYEIR-----------------
sp|Q9LKR8|RAF1_ARATH      -AQVRDSLV-QS-GAK-----PELIAAFDT-NG--AELLYEIR-----------------
XP_020878074.1            -SQVRDSLV-QS-GAK-----PELIAAFDT-GG--AELLYEIR-----------------
KAG5031773.1              -AQIR-------------------------------------------------------
KAG5045990.1              -AQIR-------------------------------------------------------
KAG5072050.1              ----DNSLVYQS-NAN-----PNLLAAFET-GD--AELLYEIR-----------------
KAH1203488.1              ----GDSLV-QS-NAD-----HDLLTAFEI-GD--AELLYEIR-----------------
KAH1203487.1              -----DSLV-QS-NAD-----HDLLTAFEI-GD--AELLYEIR-----------------
CAN61036.1                -AQVRHSLL-QS-SLD-----PQILSFFDN-GG--DSLLYEIR-----------------
XP_002268548.1            -AQVRHSLL-QS-GLD-----PQILSFFDN-GG--DSLLYEIR-----------------
RVW88115.1                -AQVRHSLL-QS-SLD-----PQILSFFDN-GG--DSLLYEIR-----------------
XP_011465980.1            -AQVRESLI-HS-KTD-----PEIMAEFDT-GG--SELLYEIR-----------------
MBA0602665.1              -SQVRESLI-QS-KTD-----EDVMSFFDT-GG--AELLYEIR-----------------
KJB80888.1                -SQVRESLI-QS-KTD-----EDVMSFFDT-GG--AELLYEIR-----------------
XP_012463925.1            -SQVRESLI-QS-KTD-----EDVMSFFDT-GG--AELLYEIR-----------------
XP_007030468.2            -AQVRESLI-QS-KTD-----ENVVSFFDT-GG--SELLYEIR-----------------
EOY10970.1                -AQVRESLI-QS-KTD-----ENVVSFFDT-GG--SELLYEIR-----------------
XP_021888657.1            -AQVRESLV-QS-NTD-----PDLVAEFDT-GG--AELLYELR-----------------
XP_002319651.1            -AQVRDSLV-QS-NTD-----PEIVASFDL-GG--AELLYEIR-----------------
XP_002521962.1            -AKVRESLT-QS-QTA-----AEIVSEFDT-GG--AELLYEIR-----------------
XP_021624035.1            -AQVRESLV-QS-NTD-----PEIVSAFDT-GG--AELLYEIR-----------------
XP_004142574.1            -AQVRESLLQSN-DSD-----PDVIASFDT-GG--AELLYEIR-----------------
XP_004495565.1            -TQVRDSLV-HS-NTD-----DQTLSFFDI-GG--AEILYEIR-----------------
XP_003590938.1            -TQVRDTLV-QA-NTD-----EEILSYFDS-GG--AEVLYEIR-----------------
AFK41237.1                -TQVRDTLV-QA-NTD-----EEILSYFDS-GG--AEVLYEIR-----------------
AGV54807.1                -TQVRDSLV-QS-NAD-----PDLLYAFET-SG--AELLYEIR-----------------
XP_007144004.1            -TQVRDSLV-QS-NAD-----PDLLYAFET-SG--AELLYEIR-----------------
XP_025980010.1            -RSK------MS-NAD-----SDLLVAFKT--G--AELLYEIR-----------------
KAG5004370.1              -AAVRGLSPVNS-PLPVKFPLPDPQNPFSLKPGSISALTPNLKATEVDKSSSIS------
KAG5152164.1              -AAVRGLSPVNS-PLPVKFPLPDPQNPFSLKPGSISALTPNLKATEVDKSSSISLAIAGA
KAG4997621.1              -AAVRGLSPVNS-PLPVKFPLPDPQNPFSLKPGSISALTPNLKATEVDKSSSIS------
XP_003536143.1            -AQVRDSLV-HS-KAD-----PDLLAAFET-GG--AELLYEIR-----------------
KAH1191965.1              -AQVRDSLV-QS-NAD-----PDLLAAFET-GG--AELLYEIR-----------------
KAG4908494.1              -AQVRDSLV-QS-NAD-----PDLLAAFET-GG--AELLYEIR-----------------
KAG5075806.1              -AAVRGLSPVNS-PMPVKFPLPDPRNPFSLKPGSISALTSNLKASEVDKSSSISLAIAGA
KAG4919720.1              ----------QN-RSP----------------G---------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              NAKIIDSLI-QS-NAD-----SDLLVAFKT--G--AELLYEIR-----------------
KAG4996767.1              NAKIIDSLI-QS-NAD-----SDLLVAFKT--G--AELLYEIR-----------------
                                                                                      

XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
PWZ36664.1                ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
sp|Q9LKR8|RAF1_ARATH      ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
KAG5072050.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              ------------------------------------------------------------
KJB80888.1                ------------------------------------------------------------
XP_012463925.1            ------------------------------------------------------------
XP_007030468.2            ------------------------------------------------------------
EOY10970.1                ------------------------------------------------------------
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ------------------------------------------------------------
KAG5152164.1              QAAATQFSKKDQNSHSTAQNNAPTNMNANNEDTEVATSYNLRSQGRSMEKGNISSTKLSK
KAG4997621.1              ------------------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              QTAATQFSKKDQNSRSTAWNNAPTNMNANNEDTEVARSYNLRSRGRSNKSEGSSKQNRSP
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            ------F-----------------------------------------------------
XP_044969817.1            ------F-----------------------------------------------------
BAJ84883.1                ------F-----------------------------------------------------
XP_044449078.1            ------F-----------------------------------------------------
XP_044322972.1            ------F-----------------------------------------------------
XP_044395281.1            ------F-----------------------------------------------------
KAF6988857.1              ------F-----------------------------------------------------
EAY78710.1                ------F-----------------------------------------------------
XP_015614647.1            ------F-----------------------------------------------------
KAB8112826.1              ------F-----------------------------------------------------
XP_004982996.1            ------F-----------------------------------------------------
XP_002448784.1            ------F-----------------------------------------------------
NP_001140763.1            ------F-----------------------------------------------------
PWZ36664.1                ------F-----------------------------------------------------
XP_016488923.1            ------L-----------------------------------------------------
XP_016475347.1            ------L-----------------------------------------------------
XP_004249913.1            ------L-----------------------------------------------------
KAH0714466.1              ------L-----------------------------------------------------
KAH0711684.1              ------L-----------------------------------------------------
XP_006350959.1            ------L-----------------------------------------------------
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ------L-----------------------------------------------------
sp|Q9LKR8|RAF1_ARATH      ------L-----------------------------------------------------
XP_020878074.1            ------L-----------------------------------------------------
KAG5031773.1              ------L-----------------------------------------------------
KAG5045990.1              ------L-----------------------------------------------------
KAG5072050.1              ------L-----------------------------------------------------
KAH1203488.1              ------L-----------------------------------------------------
KAH1203487.1              ------L-----------------------------------------------------
CAN61036.1                ------L-----------------------------------------------------
XP_002268548.1            ------L-----------------------------------------------------
RVW88115.1                ------L-----------------------------------------------------
XP_011465980.1            ------L-----------------------------------------------------
MBA0602665.1              ------L-----------------------------------------------------
KJB80888.1                ------L-----------------------------------------------------
XP_012463925.1            ------L-----------------------------------------------------
XP_007030468.2            ------L-----------------------------------------------------
EOY10970.1                ------L-----------------------------------------------------
XP_021888657.1            ------L-----------------------------------------------------
XP_002319651.1            ------L-----------------------------------------------------
XP_002521962.1            ------L-----------------------------------------------------
XP_021624035.1            ------L-----------------------------------------------------
XP_004142574.1            ------L-----------------------------------------------------
XP_004495565.1            ------L-----------------------------------------------------
XP_003590938.1            ------L-----------------------------------------------------
AFK41237.1                ------L-----------------------------------------------------
AGV54807.1                ------L-----------------------------------------------------
XP_007144004.1            ------L-----------------------------------------------------
XP_025980010.1            ------L-----------------------------------------------------
KAG5004370.1              ------L-----------------------------------------------------
KAG5152164.1              TFDDLTLPSYHEEKSSRNRSEGSSKQNRSPGAEADLRQFPQPPSKVSLSENGVFIRECER
KAG4997621.1              ------L-----------------------------------------------------
XP_003536143.1            ------L-----------------------------------------------------
KAH1191965.1              ------L-----------------------------------------------------
KAG4908494.1              ------L-----------------------------------------------------
KAG5075806.1              GAEADLM-----------------------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              ------L-----------------------------------------------------
KAG4996767.1              ------L-----------------------------------------------------
                                                                                      

XP_003573987.1            ----LNA-----------------RQRVEAAKHAIDRRLEAKGVR--------------E
XP_044969817.1            ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
BAJ84883.1                ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
XP_044449078.1            ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
XP_044322972.1            ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
XP_044395281.1            ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
KAF6988857.1              ----LNA-----------------RQRIVATKHTIERRLESKGVR--------------E
EAY78710.1                ----LNA-----------------RQRADAARHAIDRRLEPRGVR--------------E
XP_015614647.1            ----LNA-----------------RQRADAARHAIDRRLEPRGVR--------------E
KAB8112826.1              ----LNA-----------------RQRADAARHAIDRRLEPRGVR--------------E
XP_004982996.1            ----LNA-----------------RQRADAAKHAIDYRLEPKGVR--------------E
XP_002448784.1            ----LNA-----------------RQRADAARHAIDYRLEPKGVR--------------E
NP_001140763.1            ----LNA-----------------RQRADAARHAIGYRLEPKGVR--------------E
PWZ36664.1                ----LNA-----------------RQRADAARHAIGYRLEPKGVR--------------E
XP_016488923.1            ----LSA-----------------RQRADAATFLVKNGFDAKQAQ--------------D
XP_016475347.1            ----LSA-----------------RQRTDAATFLVKNGFDAKQAQ--------------D
XP_004249913.1            ----LSG-----------------KQRTDAASFIVRNGFDMKQAQ--------------D
KAH0714466.1              ----LSG-----------------KQRVDAARFMVRNGFDMKQTQ--------------D
KAH0711684.1              ----LSG-----------------KQRVDAARFMVRNGFDMKQAQ--------------D
XP_006350959.1            ----LSV-----------------KQRADAARFMVRNGFDMKQAQ--------------D
EFH61612.1                ----VSG-----------------------------------------------------
XP_002882362.1            ----LST-----------------TQRVAAATFIIDRNIDSKGAQ--------------D
sp|Q9LKR8|RAF1_ARATH      ----LNT-----------------TQRVAAAEYIVDHGFDTKGAG--------------D
XP_020878074.1            ----LNT-----------------TQRIAAAEYIVDHDFDTKGAQ--------------D
KAG5031773.1              ----LSA-----------------SQRMTTAHFLVENRCDGKAPQ--------------E
KAG5045990.1              ----LSA-----------------SQRMTTAHFLVENRCDGKAPQ--------------E
KAG5072050.1              ----LSA-----------------SQHVAAARFLVKNRCDGK------------------
KAH1203488.1              ----LSA-----------------LQHVAATSFLIENRCDGKATQ--------------E
KAH1203487.1              ----LSA-----------------LQHVAATSFLIENRCDGKATQ--------------E
CAN61036.1                ----LSA-----------------RERLAAARYVAENRVDPRGAQ--------------E
XP_002268548.1            ----LSA-----------------RERLAAARYVVENRVDPRGAQ--------------E
RVW88115.1                ----LSA-----------------RERLAAARYVAENRVDPRGAQ--------------E
XP_011465980.1            ----LSV-----------------QQRAAAARFIVEKKLDAKGAG--------------D
MBA0602665.1              ----LSA-----------------SQRAEAVRYIVENGLDAKGAQ--------------D
KJB80888.1                ----LSA-----------------SQRAEAVRYIVENGLDAKGAQ--------------D
XP_012463925.1            ----LSA-----------------SQRAEAVRYIVENGLDAKGAQ--------------D
XP_007030468.2            ----LSA-----------------KQRAEAARFILEHGLDPKGAQ--------------D
EOY10970.1                ----LSA-----------------KQRAEAARFILEHGLDPKGAQ--------------D
XP_021888657.1            ----LSA-----------------AQRAAAARFIIENRFDAKGAQ--------------D
XP_002319651.1            ----LSA-----------------TQRSAAARFIVVNKMDTKGAQ--------------D
XP_002521962.1            ----LSA-----------------PQRAAAARFIVENRLDAKGAE--------------D
XP_021624035.1            ----LSA-----------------TQRNAAARFIVEHKLDAKGAQ--------------D
XP_004142574.1            ----LST-----------------EKRAAAAKYIVENRLDSKGAQ--------------D
XP_004495565.1            ----LST-----------------SQRASVARFIVENRFDGKGAQ--------------D
XP_003590938.1            ----LST-----------------SQRAAAARFIVEKRYDGKGAQ--------------D
AFK41237.1                ----LST-----------------SQRAAAARFIVEKRYDGKGAQ--------------D
AGV54807.1                ----LST-----------------SQRVAAARFLVENNCDGKGGA--------------E
XP_007144004.1            ----LST-----------------SQRVAAARFLVENNCDGKAAQ--------------E
XP_025980010.1            ----LSA-----------------FQCITVARFLVENRCDGKATQ--------------E
KAG5004370.1              ----AIA-----------------GAQAAATQFSKKDQNSHSTAQNNAPTNMNANNEYTE
KAG5152164.1              ISVALDGEKDGYPFFILGKDEGSASQRVAAARFLVENRCDGKAAQ--------------E
KAG4997621.1              ----AIA-----------------GAQAAATQFSKKDQNSHSTAQNNAPTNMNANNEDTE
XP_003536143.1            ----LSA-----------------SQRVAAARFLVENRCDGKAAQ--------------E
KAH1191965.1              ----LSA-----------------SQRVAAARFLVENRCDGKAAQ--------------E
KAG4908494.1              ----LSA-----------------SQRVAAARFLVENRCDGKAAQ--------------E
KAG5075806.1              ----ISRRFDDKQNRSPAPLRDPPPQRVAAARFLVENRCDGKAAQ--------------E
KAG4919720.1              ------------------------AERVAAARFLVENRCDGKAAQ--------------E
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG5003541.1              ----LSA-----------------FQCITVARFLVENRCDGKATQ--------------E
KAG4996767.1              ----LSA-----------------FQCITVARFLVENRCDGKATQ--------------E
                                                                                      

XP_003573987.1            LARSMKDFPQRRG-DDG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
XP_044969817.1            LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
BAJ84883.1                LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
XP_044449078.1            LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
XP_044322972.1            LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
XP_044395281.1            LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
KAF6988857.1              LARSMKDFPQRRG-DEG-WDAFDRHSAGDCLAYARFRLSREAI-----------------
EAY78710.1                LARSMKDFPQRRG-DDG-WEAFTRDNPGDCLAFARFRQSREAI-----------------
XP_015614647.1            LARSMKDFPQRRG-DDG-WEAFTRDNPGDCLAFARFRQSREAI-----------------
KAB8112826.1              LARSMKDFPQRRG-DDG-WEAFTRDNPGDCLAFARFRQSREAI-----------------
XP_004982996.1            LARSMKDFPRRRAVDEG-WEAFDGASPGDCLAFARFRQSREAI-----------------
XP_002448784.1            LARAMKGFPRWRG-EEG-WEAFGRDSPADCLAYARFRQSREAI-----------------
NP_001140763.1            LARAMKGFPRWRG-EEG-WEAFSKDSPADCLAFARFRQSREAI-----------------
PWZ36664.1                LARAMKGFPRWRG-EEG-WEAFSKDSPADCLAFARFRQSREAI-----------------
XP_016488923.1            LARAIKDYPRRRV-EYG-WDKFHGDSPGDCLAFMYFRLAQEYA--AA-------------
XP_016475347.1            LARAIKDYPRRRV-DYG-WDKFNGDSPGDCLAFMYFRLAQEYA----AA-----------
XP_004249913.1            LARSMKDFPRRRI-DYG-WDKFTGDSPGDCLAFWFFRLAQEHAAA---------------
KAH0714466.1              LARAMKDFPRRRI-DYG-WDKFTGDSPGDCLAFWFFRLAQEHA-----------------
KAH0711684.1              LARAMKDFPRRRI-DYG-WDKFTGDSPGDCLAFWFFRLAQEHA-----------------
XP_006350959.1            LARAMKDFPRRRI-DYG-WDKFTGDSPGDCLAFWFFRLAQEHA-----------------
EFH61612.1                --------------DRQ-------------------------------------------
XP_002882362.1            LARAIKDYPNRRG-DVG-WLDFDYNLPGDCLSFLYYRQSRENK-----------------
sp|Q9LKR8|RAF1_ARATH      LARAIKDFPHRRG-DVG-LGDFDYNLPGDCLSFMLYRKSREHR-----------------
XP_020878074.1            LARAIKDYPHRRG-DVG-WEDFDYNLPGDCLSFMLYRKSREYR-----------------
KAG5031773.1              LAPSVKDFPSRRE-DKGLWNG-ERGGYGGC---------R--------------------
KAG5045990.1              LAPSVKDFPSRRE-DKGLWNG-ERGGYGGCR-----------------------------
KAG5072050.1              --------------------------------------SREHR-----------------
KAH1203488.1              LAHAMKAFP-----NKG-WESFDYTLPEDCLSF---------------------------
KAH1203487.1              LAHAMKAFP-----NKG-WESFDYTLPEDCLSF---------------------------
CAN61036.1                LARAIKDFPRRRG-DRG-WECFDYNVPGDCLAFMYYRQSREHR-----------------
XP_002268548.1            LARAIKDFPRRRG-DRG-WECFDYNVPGDCLAFMYYRQSREHR-----------------
RVW88115.1                LARAIKDFPRRRG-DRG-WECFDYNVPGDCLAFMYYRQSREHR-----------------
XP_011465980.1            LARATKDFPRRRG-DKG-WESFDYTNPGDCLAFMYYRQAREHN-----------------
MBA0602665.1              LARAMKDFPRRKM-DKG-WKSFEYGLPGDCLSFMYYRLSREHG-----------------
KJB80888.1                LARAMKDFPRRKM-DKG-WKSFEYGLPGDCLSFMYYRLSREHG-----------------
XP_012463925.1            LARAMKDFPRRKM-DKG-WKSFEYGLPGDCLSFMYYRLSREHG-----------------
XP_007030468.2            LARAMKDFARRKT-DKG-WKSFDYQLPGDCLSFMYYRQSREHK-----------------
EOY10970.1                LARAMKDFARRKT-DKG-WKSFDYQLPGDCLSFMYYRQSREHK-----------------
XP_021888657.1            LARAMKDYPRRRG-DRG-WDFFDYSLPGDCLSFMYYRQSREHQ-----------------
XP_002319651.1            LARAMKDFPRRRG-DKF-WESFDYVLPGDCLSFMYYRQSREHK-----------------
XP_002521962.1            LARAMKDFPRRRG-DKG-WESFDYTLPGDCLSFMYYRQSREHK-----------------
XP_021624035.1            LARAMKDYPRRRG-EKA-WESFDYNLPGDCLSFMYYRQAREHN-----------------
XP_004142574.1            LARAMKDFPRRRG-DKG-WEYFDYDFAGDCLAYMYYRLSREYN-----------------
XP_004495565.1            IARSIKDFPKRRG-EKG-WESFDYTLPGDCLSYMYYRQSREHT-----------------
XP_003590938.1            LARSIKDFPSRRG-EKH-WESFDYHLPGDCLAYLYYRQSKENK-----------------
AFK41237.1                LARSIKDFPSRRG-EKH-WESFDYHLPGDCLAYLYYRQSKENK-----------------
AGV54807.1                LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQGREHK-----------------
XP_007144004.1            LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQGREHK-----------------
XP_025980010.1            LARAMKDFPSRHG-DKG-WESFDYTLLEDCLSFMYYRQSREHR-----------------
KAG5004370.1              VATSYNLRSQGRSMEKGNISSTKLSKTFDDLTLPSYHEEKSSRNRSEGSSKQNRSPGAEA
KAG5152164.1              LARSMKDFPSRRG-DKG-WARFDYTLPGDCLSFMYYRQSREHR-----------------
KAG4997621.1              VATSYNLRSQGRSMEKGNISSTKLSKTFDDLTLPSYHEEKSSRNRSEGSSKQNRSPGAEA
XP_003536143.1            LARSMKDFPSRRG-DKG-WARFDYTLPGDCLSFMYYRQSREHR-----------------
KAH1191965.1              LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQSKEHR-----------------
KAG4908494.1              LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQSKEHR-----------------
KAG5075806.1              LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQSKEHR-----------------
KAG4919720.1              LARAMKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQSKEHR-----------------
KAG4395437.1              ----MKDFPSRRG-DKG-WESFDYTLPGDCLSFMYYRQSKEHR-----------------
KRH13534.1                ----MKDFPSKRG-DKG-WESFDYTLERDCLSFMYYWQSREHR-----------------
XP_006598154.1            ----MKDFPSKRG-DKG-WESFDYTLERDCLSFMYYWQSREHR-----------------
XP_040865419.1            ----MKDFPSKRG-DKG-WESFDYTLERDCLSFMYYWQSREHR-----------------
KAG5003541.1              LARAMKDFPSRHG-DKG-WESFDYTLLEDCLSFMYYRQSREHR-----------------
KAG4996767.1              LARAMKDFPSRHG-DKG-WESFDYTLLEDCLSFMYYRQSREHR-----------------
                                                                                      

XP_003573987.1            ----------------------ANEDRMPELERSLDVVETETARARVELEMERAIRKAAG
XP_044969817.1            ----------------------ANEDRIPELERSLDVVETESARARVELEMERAIKKAAG
BAJ84883.1                ----------------------ANEDRIPELERSLDVVETESARARVELEVERAIKKAAG
XP_044449078.1            ----------------------ANEDRIPELERSLDVVETESARARVELEIERAIKKAAG
XP_044322972.1            ----------------------ANEDRIPELERSLDVVETESARARVELEIERAIKKAAG
XP_044395281.1            ----------------------ANEDRIPELERSLDVVETESARARVELEIEKAIKKAAG
KAF6988857.1              ----------------------ANEDRIPELERSLDVVETESARARVELEIEKAIKKAAG
EAY78710.1                ----------------------DAEDSVAELERALEVVDTEPARARVEAELDRARRKAAG
XP_015614647.1            ----------------------DAEDSVAELERALEVVDTEPARARVEAELDRARRKAAG
KAB8112826.1              ----------------------DAEDSVAELERALEVVDTEPARARVEAELDRARRKAAG
XP_004982996.1            ----------------------DVDDRIAELNRALQVVATETARARLELEMERARKKAAG
XP_002448784.1            ----------------------DVEERIAELERALQVVETESGRARVELELERARKKAAG
NP_001140763.1            ----------------------DVQDRVAELERALQVVETESGRARVELELERARRKAAG
PWZ36664.1                ----------------------DVQDRVAELERALQ------------------------
XP_016488923.1            ---------------------ASEDLRRSSMEKALEVAESESARNLLVMELEGNE-----
XP_016475347.1            ---------------------ASEDLRRSSMEKALEVVESESARNLLVMELEGRE-----
XP_004249913.1            ---------------------AAEDSRVEAMEKALEVVETESARNVLVEVLEGKG-----
KAH0714466.1              -------------------AAAAEDSRVEAMEKALEVVDTESARNVLVEVLEGKG-----
KAH0711684.1              -------------------AAAAEESRVEAMEKALEVVETESARNVLVEVLEGKG-----
XP_006350959.1            -------------------AAAAEESRVEAMEKALEVVETESARNVLVEVLEGKG-----
EFH61612.1                ------------------------------------------------------------
XP_002882362.1            ---------------------NPSEQRTSMLLQALGVVESEKAKNKLNKELYGEK-----
sp|Q9LKR8|RAF1_ARATH      ---------------------SPSEIRTTLLEQALETAVTEKAKKAVLRELHGES-----
XP_020878074.1            ---------------------SPSEIRTTLLEQALETAVTEKAKKAVTRELHGES-----
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
KAG5072050.1              ---------------------NLSEQRTSML----GMAETKATTNVILEELEGKG-----
KAH1203488.1              ---------------------EPVGAEDSALEQALGVAETKAVTNVILEELEGKG-----
KAH1203487.1              ---------------------EPVGAEDSALEQALGVAETKAVTNVILEELEGKG-----
CAN61036.1                ---------------------NSLDKRRAALEKALEVAETEKAKRVLLEELERND-----
XP_002268548.1            ---------------------NSLDKRRAALEKALEVAETEKAKRVLLEELERND-----
RVW88115.1                ---------------------NSLDKRRAALEKALEVAETEKAKRVLLEELERND-----
XP_011465980.1            ---------------------DMSETRTDALEEALKVVGSEKARSVIVRELEGAS-----
MBA0602665.1              ---------------------NPSEQRTAALMQALQVAESESAKKEVSEELEGGE-----
KJB80888.1                ---------------------NPSEQRTAALMQALQVAESESAKKEVSEELEGGE-----
XP_012463925.1            ---------------------NPSEQRTAALMQALQVAESESAKKEVSEELEGGE-----
XP_007030468.2            ---------------------NPSEQRTSALRQALKVAESESAKKELLEELECGE-----
EOY10970.1                ---------------------NPSEQRTSALRQALKVAESESAKKELLEELECGE-----
XP_021888657.1            ---------------------NPSSERTAALQQALEVAESEKAKGEVSRELEGDS-----
XP_002319651.1            ---------------------NPSESRTNALQMALEVAESEKAKSAILKELEGGG-----
XP_002521962.1            ---------------------TPSEPRTNALERALDVAESEKAKNEVLKELEGDS-----
XP_021624035.1            ---------------------NPSELRTNTLEMAMDVAESEKAKSAVLGELKREG-----
XP_004142574.1            ---------------------SSTERRTAALEEALKVVVTEKARDLIVGDLEGKG-----
XP_004495565.1            ---------------------NPSDQRTAALELALSVVQSEKAKKVILEELEGKV-----
XP_003590938.1            ---------------------NPSDPRTAFLQQALSAVESDKARNVILEELNGKA-----
AFK41237.1                ---------------------NPSDPRTAFLQQALSAVESDKARNVILEELSGKA-----
AGV54807.1                ---------------------NPSDQRSSALEQALRVAETEKARKVVLEELEGNE-----
XP_007144004.1            ---------------------NPSDQRSSALEQALRVAETEKARKVVLEELEGNE-----
XP_025980010.1            ---------------------NPSKQRTSVLE----------------------------
KAG5004370.1              DLRQFPQPPSKVSLSENGVFMNPSEQRTSALEQALRVAETEAARNMILEELEGNG-----
KAG5152164.1              ---------------------NPSEQRTSALEQALRVAETEAARNMILEELEGNG-----
KAG4997621.1              DLRQFPQPPSKVSLSENGVFMNPSEQRTSALEQALRVAETEAARNMILEELEGNG-----
XP_003536143.1            ---------------------NPSEQRTSALEQALRVAETEAARNMILEELEGNG-----
KAH1191965.1              ---------------------NPSEQRTSALEQALRVAETEAARNVILEELEGKG-----
KAG4908494.1              ---------------------NPSEQRTSALEQALRVAETEAARNVILEELEGKG-----
KAG5075806.1              ---------------------NPSEQRTSALEQALRVAETEAARNVILEELEGKG-----
KAG4919720.1              ---------------------NPSEQRTSALEQALRVAETEAARNVILEELEGKG-----
KAG4395437.1              ---------------------NPSEQRTSALEQALRVAETEAARNVILEELEGKG-----
KRH13534.1                ---------------------NPSEQRTSALEQGLGVAEMEAARNVILEELEGKG-----
XP_006598154.1            ---------------------NPSEQRTSALEQGLGVAEMEAARNVILEELEGKG-----
XP_040865419.1            ---------------------NPSEQRTSALEQGLGVAEMEAARNVILEELEGKG-----
KAG5003541.1              ---------------------NPSKQRTSVLE----------------------------
KAG4996767.1              ---------------------NPSKQRTSVLE----------------------------
                                                                                      

XP_003573987.1            -----EEVEE----PEADVNARPAVPVVRLIYGEISEASIVLLLPVVRETDGVEAVDLAP
XP_044969817.1            -----EEVEE----LEAKVDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVQAVDLAP
BAJ84883.1                -----EEVEE----LEAKVDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVQAVDLAP
XP_044449078.1            -----EEVEE----LEAEIDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVKAVDLAP
XP_044322972.1            -----EEVEE----LEAEIDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVKAVDLAP
XP_044395281.1            -----EEVEE----LEAEVDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVKAVDLAP
KAF6988857.1              -----EEVEE----LEAEVDARPAVPVVRLMYGEISEASIVLLLPVVKETDGVKAVDLAP
EAY78710.1                EEVDDEDGAA----NAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREGDGGEALAHAP
XP_015614647.1            EEVDDEDGAA----NAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREGDGGEALAHAP
KAB8112826.1              EEVDDEDGAA----NAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREGDGGEALAHAP
XP_004982996.1            -----EEVEE----GEDDTASRPAVNVVRLQYGEVAEASTVLLLPVVRETDGVAAMESAP
XP_002448784.1            -----EEVVE----EDDPAASRPNVTVVRLQYGEVAEATTVFMLPVVRETDGVAAMESAP
NP_001140763.1            EEEVDEEGEE----DDAAASLRPGVTVVRLRYGEVAEATTVILLPVVRETDGVAAMESAP
PWZ36664.1                ----------------------------------VAEATTVILLPVVRETDGVAAMESAP
XP_016488923.1            -----VAKES-------VKDDGVTVPLVRMKLGEVAESTIVVVLPVCKAEGRDVEVEAAP
XP_016475347.1            -----VAKES-------VLDDGVTVPLVRMKLGEVAESTIVVVLPVCKAEGRDVEVEAAP
XP_004249913.1            -----VDKES-------VIDEQVKVPLVRMKLGEVAESTKVVVLPVCKAEKREFEVEAAP
KAH0714466.1              -----VDKDS-------VIDEQVKVPLVRMKLGEVAESTKVVVLPVCKAEKREFEVEAAP
KAH0711684.1              -----VDKDS-------VIDEQVKVPLVRMKLGEVAESTKVVVLPVCKAEKREFEVEAAP
XP_006350959.1            -----VDKDS-------VIDEQVKVPLVRMKLGEVAESTKVVVLPVCKAEKREFEVEAAP
EFH61612.1                -------------------------PIVISQY----------------------------
XP_002882362.1            -----EEEKEKEKKKKEEEVKAIRIPVVRLKFGEVAGASSVVVLPVCKAEEGEKKILEAP
sp|Q9LKR8|RAF1_ARATH      -----EEERV-----KEEEIKIIRVPVVRLRFGEVAGASSVVVLPVCKAEEGEEKLLEAP
XP_020878074.1            -----EEERA-----KEEEIKIIRVPVVRLRFGEVAGASSVVVLPVCKAEEGEEKLLEAP
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
KAG5072050.1              -----EEGDT-----VGEGEAATRVPVVRLRIGEVAKVSSVVLLSVFATEE--KEILEA-
KAH1203488.1              -----EEGDT-----VGEREAAAHVPVVRLRIGEVAEVSSVVLLPVFATEE--KEILEAC
KAH1203487.1              -----EEGDT-----VGEREAAAHVPVVRLRIGEVAEVSSVVLLPVFATEE--KEILEAC
CAN61036.1                -----DADDG-----KSEIEEAVRVPVVRMKTGEVAEATTV------------SGITGAP
XP_002268548.1            -----DADDG-----KSEIEGAVRVPVVRMKTGEVAEATTVVVLPVCEAQEGVDVVLGAP
RVW88115.1                -----DADDG-----KSEIEEAVRVPVVRMKTGEVAEATTVVVLPVCEAQEGVDVVLGAP
XP_011465980.1            -----VRDEE------EEVVAVVKVPVVRLKFGEVGESSRVVVLPVCKAEEKDKEVMEAP
MBA0602665.1              -----DEKPE----KDDDLEYRVRVPVVRMQFGEVAEATSVVVLPVCMAEEDTKELLEAP
KJB80888.1                -----DEKPE----KDDDLEYRVRVPVVRMQFGEVAEATSVVVLPVCMAEEDTKELLEAP
XP_012463925.1            -----DEKPE----KDDDLEYRVRVPVVRMQFGEVAEATSVVVLPVCMAEEDTKELLEAP
XP_007030468.2            -----DGKEE----KEEDLDYGVRVPVVRLKIGEVAEASSVVVLPVCKAEEKDREILQAP
EOY10970.1                -----DGKEE----KEEDLDYGVRVPVVRLKIGEVAEASSVVVLPVCKAEEKDREILQAP
XP_021888657.1            -----EKKGG----KEDGVEGTVRVPVVRMKIGEVAEASSVVVLPVCRAEESEAELLEVP
XP_002319651.1            -----ERKER----AEGETADGVRVPVVRLKIGEVAEATSVVVLPVCRSEDGERKIVEAP
XP_002521962.1            -----EGKEE----KEGEVGDATRVPVVRLRIGEVAEATSVVVLPVCRALQKEKEIWEAP
XP_021624035.1            -----EGEDA----KEEETGDGVRVPVVRLRIGEVAEATRVVVLPVCKAEEREREILEAP
XP_004142574.1            -----DGKDG----VEEEIGAAVKVPVVRMKIGEVAEATTVVVMPVCKAGEGEKGVGEAP
XP_004495565.1            -----ESVVE-------DVVIKVSVPVVRLKIGEVAESSSVIVLPVVKAEEGDKVILEAP
XP_003590938.1            -----EEEKV------EDVVLKVPVNVVRLKIGEVAEATSVVVLPVCKAEEGERVIMEAP
AFK41237.1                -----EEEKV------EDVVLKVPVNVVRLKIGEVAEATSVVVLPVCKAEEGERVIMETP
AGV54807.1                -----EEDKV-------EDGERVRVPVVRLRIGEVAEASSVVVLPVCGAEE--KEVLEAP
XP_007144004.1            -----EEDKV-------EDGERVRVPVVRLRIGEVAEASSVVVLPVCGAEE--KEVLEAP
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              -----EEGDK-----VDAGEGAVRVPVVRLRIGEVAEASSVVVLPVSAAEE--REILEAP
KAG5152164.1              -----EEGDK-----VDAGEGAVRVPVVRLRIGEVAEASSVVVLPVSAAEE--REILEAP
KAG4997621.1              -----EEGDK-----VDAGEGAVRVPVVRLRIGEVAEASSVVVLPVSAAEE--REILEAP
XP_003536143.1            -----EEGDK-----VDAGEGAVRVPVVRLRIGEVAEASSVVVLPVSAAEE--REILEAP
KAH1191965.1              -----EEGDT-----VGEGEAAARVPVVRLRIGEVAEASSVVLLPVSAAEE--REILEAP
KAG4908494.1              -----EEGDT-----VGEGEAAARVPVVRLRIGEVAEASSVVLLPVSAAEE--REILEAP
KAG5075806.1              -----EEGDT-----VGEGEAAARVPVVRLRIGEVAEASSVVLLPVSAAEE--REILEAP
KAG4919720.1              -----EEGDT-----VGEGEAAARVPVVRLRIGEVAEASSVVLLPVSAAEE--REILEAP
KAG4395437.1              -----EEGDT-----VGEGEAAARVPVVRLRIGEVAEASSVVLLPVSAAEE--REILEAP
KRH13534.1                -----VSEKK-----------------IQKQTVSLMAASFRWILQLH------KDVPKAA
XP_006598154.1            -----VSEKK-----------------IQKQTVSLMAASFRWILQLH------KDVPKAA
XP_040865419.1            -----VSEKK-----------------IQKQTVSLMAASFRWILQLH------KDVPKAA
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            RRKKTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIQLADGR-VLPWRS---
XP_044969817.1            RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VLPWRS---
BAJ84883.1                RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VLPWRS---
XP_044449078.1            RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VLPWRS---
XP_044322972.1            RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VLPWRS---
XP_044395281.1            RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VMPWRS---
KAF6988857.1              RRSQTDADL---GIVEVDKGWARWAVLPGWAPVMAVADEA-VVIELADGR-VMPWRS---
EAY78710.1                RRTRTDADL---GMVEVDKGWTRWAVVPGWGPVAEVAGEA-VVIELADGR-TLPWRS---
XP_015614647.1            RRTRTDADL---GMVEVDKGWTRWAVVPGWGPVAEVAGEA-VVIELADGR-TLPWRS---
KAB8112826.1              RRTRTDADL---GMVEVDKGWTRWAVVPGWGPVAEVAGEA-VVIELADGR-TLPWRS---
XP_004982996.1            RRTKTDVDL---GIVEVDKAWARWAVVPGWGPVAAAAEEA-VAIELADGR-RLPWRT---
XP_002448784.1            RRTKTDVDL---GIVEVDKAWARWAVLPGWGPVAEAADDA-VVVELADGR-RLPWRT---
NP_001140763.1            RRAKTDVGL---GVVEVDRAWARWAVVPGWGPVAEAADDA-VVVELADGR-RLPWRM---
PWZ36664.1                RRAKTDVGL---GVVEVDRAWARWAVVPGWGPVAEAADDA-VVVELADGR-RLPWRM---
XP_016488923.1            WECGGVGDF---GIVEAEKDWRRWVVLPGWQPIAGLERGG-VAVSFKSGN-FLPWRE-KS
XP_016475347.1            WECGGVGDF---GIVEAEKDWRRWVVLPGWQPIAGLERGG-VAVSFKSGN-FLPWRE-KS
XP_004249913.1            WECGGVGEF---GVVEAEKDWRRWVVLPGWQPIAGLERGG-VAVSFKNGK-LLPWKE-KR
KAH0714466.1              WECDGVGDF---GIVEVEKDWRRWVVLPGWQPIAGLERGG-VAVSFKSGK-LLPWKE-KR
KAH0711684.1              WECGGVGDF---GVVEAEKDWRRWVVLPGWQPIAGLERGG-VAVSFKSGK-LLPWKE-KR
XP_006350959.1            WECGGVGDF---GVVEAEKDWRRWVVLPGWQPIAGLERGG-VAVSFKSGK-LLPWKE-KR
EFH61612.1                ----QTNHF---G--------------------------------------VKPLNH---
XP_002882362.1            MEIIAGGDF---KVVEAEKGWKRWVVLPGWNPVAAIGKGG-VAVSFRDDRKVLPCDG---
sp|Q9LKR8|RAF1_ARATH      MEFESGGEF---GVVEAEKDWSRWVVLPGWDPVVAVRKG--VAVSFSDDREVLPWNG---
XP_020878074.1            MEFESGGEF---GVVEAEKDWSRWVVLPGWEPVVAVRKGG-VAVSFSDDREVLPWNG---
KAG5031773.1              ------------GCCMCSGG---------------------------EAK---DWGG---
KAG5045990.1              ------------GCCMCSGG---------------------------EAK---DW-----
KAG5072050.1              --------------CIISRQISLWIRPPPYSLLYGS-----ILVINTHSR---QYRD---
KAH1203488.1              KISSKETYI--------------------------------LLIPLGCLH-LFP------
KAH1203487.1              KIRLYDLRLLQRGVVQCYEGH----VNSHTHMQISVDPSERFVMSGGEDCKLKLWSI---
CAN61036.1                LECRSQGEF---GVVVAEKGWKRWVVLPGWEPVAGLRAG--VVVAFGDAR-ALPWRV-NR
XP_002268548.1            LECRSQGEF---GVVVAEKGWKRWVVLPGWEPVAGLRAG--VVVAFGDAR-ALPWRV-NR
RVW88115.1                LECRSQGEF---GVVVAEKGWKRWVVLPGWEPVAGLRAG--VVVAFGDAR-ALPWRV-NR
XP_011465980.1            WECESEGEL---GVVVAEKGWKRWVVLPGWEPVVGLGKGG-VVVSFSDAR-VLPWKV-NR
MBA0602665.1              LECRSGGDF---GVVEAEKGWKRWVVLPSWEPLAGLRHGG-VVVAFSDAR-VIQWKS-NR
KJB80888.1                LECRSGGDF---GVVEAEKGWKRWVVLPSWEPLAGLRHGG-VVVAFSDAR-VIQWKS-NR
XP_012463925.1            LECRSGGDF---GVVEAEKGWKRWVVLPSWEPLAGLRHGG-VVVAFSDAR-VIQWKS-NR
XP_007030468.2            LECRSKGDF---GVVEAEKGWNRWVVLPGWEPVVGLSNGG-VVVAFGDAR-GLPWKA-NR
EOY10970.1                LECRSKGDF---GVVEAEKGWNRWVVLPGWEPVVGLSNGG-VVVAFGDAR-GLPWKA-NR
XP_021888657.1            WECKSKGEF---GVVVSEKGWKRWVVLPGWEPVAGLGNGG-VVVAFGDAR-ALPWKT-KR
XP_002319651.1            WECKGQGEF---GVVVAEKAWERWVVLPGWEPVLGLGRGG-VAVAFPDAR-VLPWKA-NR
XP_002521962.1            WECKSEGEF---GVVVAEKGWERWVVLPGWEPVVGLEKGG-VVVAFPDAR-ALPWKV-NR
XP_021624035.1            WECRTEGEF---GVVAAEKGWKRWVVLPSWEPLVGLEKGG-VVVAFADAR-ALPWKA-NR
XP_004142574.1            MEVRSEGEF---GVVVAEKGWSRWVVLPGWEPVAGLVKGGGVVVAFEDAR-VLPWRV-NR
XP_004495565.1            SEMRNEGVF---GVVVAEKGWERWVVLPSWDPIVNLGKGG-VVVSFIDAR-VLPWKA-NK
XP_003590938.1            SEIRKEGEF---GIVVAEKGWEKWVVLPAWGPVVNLGKG--VVVSFLDAR-VLPWKANNR
AFK41237.1                SEIRKEGEF---GIVVAEKGWEKWVVLPAWGPVVNLGKG--VVVSFLDAR-VLPWKANNR
AGV54807.1                FECRSEGEF---GVVVAEKGWARWVVLPWWEPVVGLIKGG-VVVSFPDAR-VLPWKA-NR
XP_007144004.1            FECRSEGEF---GVVVAEKGWARWVVLPWWEPVVGLIKGG-VVVSFPDAR-VLPWKA-NR
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              YESRSQGVF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG5152164.1              YESRSQGVF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG4997621.1              YESRSQGVF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
XP_003536143.1            YESRSQGVF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAH1191965.1              FESRSQGEF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG4908494.1              FESRSQGEF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG5075806.1              FESRSQGEF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG4919720.1              FESRSQGEF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KAG4395437.1              FESRSQGEF---GVVVAEKGWGKWVVLPSWDPVVGLGKGG-VVVSFPDAR-VLPWKV-NR
KRH13534.1                RFYSEGLDF---SINVCSLRW------------AELQSGS-LKVALVHSP-NEQQQATQK
XP_006598154.1            RFYSEGLDF---SINVCSLRW------------AELQSGS-LKVALVHSP-NEQQQATQK
XP_040865419.1            RFYSEGLDF---SINVCSLRW------------AELQSGS-LKVALVHSP-NEQQQATQK
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGNK-LLEEGIITA
XP_044969817.1            -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGNK-LLEEGISQA
BAJ84883.1                -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGNK-LLEEGISQA
XP_044449078.1            -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGKK-LLEEGISQA
XP_044322972.1            -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGKK-LLEEGISQA
XP_044395281.1            -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGKK-LLEEGISQA
KAF6988857.1              -AENERVLVVADRKRKEV-VDEGIYVLEK-------GG--KLVVE-RGKK-LLEEGISQA
EAY78710.1                -AEAERVLVVANRGRREV-VEDGIYVVER-------EG--RLVVE-KGRK-LAAEGVGEA
XP_015614647.1            -AEAERVLVVANRGRREV-VEDGIYVVER-------EG--RLVVE-KGRK-LAAEGVGEA
KAB8112826.1              -AEAERVLVVANRGRREV-VEDGIYVVER-------EG--RLVVE-KGRK-LAAEGVGEA
XP_004982996.1            -AEEEPVLVIANRGQKEV-AEQGSYVLEK-------EG--RLVVE-RGRK-LAEQGITVA
XP_002448784.1            -ADEEPVLVIANRSKKEV-VEQGIYVLEK-------DG--RLVVE-RGKK-LAEQGIAAA
NP_001140763.1            -SDEEPVLVIANRSKKEV-VEEGVYVLER-------EG--RLVVE-RGKK-LAEQGIAAA
PWZ36664.1                -SDEEPVLVIANRSKKEV-VEEGVYVLER-------EG--RLVVE-RGKK-LAEQGIAAA
XP_016488923.1            KYKQEPVLVVADRGRTEVASEDGFYLVVD-GGNGSNEE--GLKVE-RGST-LKKRGVEQS
XP_016475347.1            KYKQEPVLVVADRGRTEVASEDGFYLVVD-GGDGSNEE--GLKVE-RGST-LKKRGVEQS
XP_004249913.1            KYKEEPVLVVADRGRKEVVVDDGFYLVLS-GGNGSGDE--GLKVE-RGLN-LKEMGVEMS
KAH0714466.1              KYKEEPVLVVADRGRKEVVVDDGFYLVLS---GGNGSGDEGLMVE-RGLT-LKEMGVEKS
KAH0711684.1              KYKEEPVLVVADRGRKEVVVDDGFYLVLS---GGNGSGDEGLMVE-KGLT-LKEMGVEKS
XP_006350959.1            KYKEEPVLVVADRGRKEVVVDDGFYLVLS---GGNGSGDEGLMVE-KGLT-LKEMGVEKS
EFH61612.1                -----------------LIYDEGLIISTC-----------GMKLD-RGSV-LKEKGVNES
XP_002882362.1            --KEEPLLVVTDRVRNFVEADDGYFLVVA-------EN--GLKLE-KGSE-LKAREVKES
sp|Q9LKR8|RAF1_ARATH      --KGEAIMVVIDREKKTVEADNGYYYLVV------ADG--GMKLD-RGLV-LKEKGVNES
XP_020878074.1            --KEEAIMVVIDREKKTVEADNGYYYLVV------AEG--GMKLD-RGSV-LKEKGVNES
KAG5031773.1              -------------------------------------G--GSKFG-GGVA-GLRDG----
KAG5045990.1              -----------------------------------GGG--GSKFG-GGVA-GLRDG----
KAG5072050.1              --KEAPEL-----------PESGFQFLDR-------------------DV-DAADLISFM
KAH1203488.1              ----------------------------------------GLE-----------------
KAH1203487.1              ---KSGELLFEDKFSDSVISIVCYKTYGH-----------SFKAE-EENQYKHDSSQGAW
CAN61036.1                WYKEEAILVVANRGAKEVVADAGFYLVAVSSDNGSAGG--ELKVE-RGSA-LKERGVKES
XP_002268548.1            WYKEEAILVVANRGAKEVVADAGFYLVAVSSDNGSAGG--ELKVE-RGSA-LKERGVKES
RVW88115.1                WYKEEAILVVANRGAKEVVADAGFYLVAVSSDNGSAGG--ELKVE-RGSA-LKERGVKES
XP_011465980.1            WYKEEPILVVADRSKKEVEADDGFYLAAV------DGEGLGFKVE-RGSA-LKEAGVKES
MBA0602665.1              WYKEEAILVVTDRNRKEVEVDAAFYLAMV------DGG--GLKVD-TGSA-LKEMGVKES
KJB80888.1                WYKEEAILVVTDRNRKEVEVDAAFYLAMV------DGG--GLKVD-TGSA-LKEMGVKES
XP_012463925.1            WYKEEAILVVTDRNRKEVEVDAAFYLAMV------DGG--GLKVD-TGSA-LKEMGVKES
XP_007030468.2            WYKEEPILVVADRSRKEVEFDDGFYLVTV------DSG--ELKVD-RGSA-LKETGVKES
EOY10970.1                WYKEEPILVVADRSRKEVEFDDGFYLVTV------DSG--ELKVD-RGSA-LKETGVKES
XP_021888657.1            WYKEEPVLVVADRGRKEVKADDGFYLVNV---ADDNGA--GLKIE-RGLS-LKEAGVEES
XP_002319651.1            WYKEESILVVADRGSKEVKADDGFYLVTL----DGAGG--DFKVE-RGSA-LKERNVVEC
XP_002521962.1            WYKEEAILVVADRGSKEVNANDGFYLVAVDGSGDGRSG--GLEVE-RGSI-LKERGVEES
XP_021624035.1            WYKEEAILVVADRGRKEVNVDSGFYLMAVADNGDGRSG--ALKVE-RGSE-LKERGVGES
XP_004142574.1            WYKEEPILVVADRSRREVVAGDGFYLMGG----GDGGG--DLKVE-RGNA-LMEMGVKES
XP_004495565.1            WYKEEPILVVADRSKREVENDDGFYLVKV------DGDELGLKVQ-RGLA-LKEMGVGEC
XP_003590938.1            WCKEEPILVVADRSKREVENDDGFYLVKD------DGNDVGLKVQ-RGSI-LKEMGVNEC
AFK41237.1                WCKEEPILVVADRSKREVENDDGFYLVKD------DGNDVGLKVQ-RGSI-LKEMGVNEC
AGV54807.1                WYKEEAVLVVADRSKREVGADDGFYLVNG------YGDDGGLKVE-RGLT-LKEKGFTQS
XP_007144004.1            WYKEEAVLVVADRSKREVGADDGFYLVNG----YGDDG--GLKVE-RGLT-LKEKGFTQS
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              WYKEEPILVVADRSKKEVGADDGFYLVNA------DGE--GLKVE-RGSG-LKEKGFTQS
KAG5152164.1              WYKEEPILVVADRSKKEVGADDGFYLVNA------DGE--GLKVE-RGSG-LKEKGFTQS
KAG4997621.1              WYKEEPILVVADRSKKEVGADDGFYLVNA------DGE--GLKVE-RGSG-LKEKGFTQS
XP_003536143.1            WYKEEPILVVADRSKKEVGADDGFYLVNA------DGE--GLKVE-RGSG-LKEKGFTQS
KAH1191965.1              WYKEEPILVVANRSNREVGADHGFYLVNS------DAE--GLKVQ-RGFA-LKEKGFTQS
KAG4908494.1              WYKEEPILVVANRSNREVGADHGFYLVNS------DAE--GLKVQ-RGFA-LKEKGFTQS
KAG5075806.1              WYKEEPILVVANRSNREVGADHGFYLVNS--------DAEGLKVQ-RGFA-LKEKGFTQS
KAG4919720.1              WYKEEPILVVANRSNREVGADHGFYLVNS------DAE--GLKVQ-RGFA-LKEKGFTQS
KAG4395437.1              WYKEEPILVVANRSNREVGADHGFYLVNS------DAE--GLKVQ-RGFA-LKEKGFTQS
KRH13534.1                GYSSLLSFTVNDMNNT---VTKLMALGAE------LDGPIKYEVHGKGEDLLRESGIPYA
XP_006598154.1            GYSSLLSFTVNDMNNT---VTKLMALGAE------LDG--PIKYEVHGKV----AAMRCI
XP_040865419.1            GYSSLLSFTVNDMNNT---VTKLMALGAE------LDG--PIKYEVHGKV----AAMRCI
KAG5003541.1              ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
                                                                                      

XP_003573987.1            AAEVVTVVRPPK-DEED--IIVGDEWD----
XP_044969817.1            AAEVVTVVRPPK-DEED--IIVGDEWD----
BAJ84883.1                AAEVVTVVRPPK-DEED--IIVGDEWD----
XP_044449078.1            AAEVVTVVRPPK-DEED--IIVGDEWD----
XP_044322972.1            AAEVVTVVRPPK-DEED--IIVGDEWD----
XP_044395281.1            AAEVVTVVRPPK-DEED--IIVGDEWD----
KAF6988857.1              AAEVVTVVRPPK-DEED--IIVGDEWD----
EAY78710.1                AAEVLVVVRPPR-DEDD--MISDDEWD----
XP_015614647.1            AAEVLVVVRPPR-DEDD--MISDDEWD----
KAB8112826.1              AAEVLVVVRPPR-DEDD--MISDDEWD----
XP_004982996.1            AAEVLIVVRPPR-DEDE--MISDEEWD----
XP_002448784.1            AAEVVIVVRPPK-DEDG--MISDEEWD----
NP_001140763.1            AAEVVIVVRPPK-DEDD--MVSDEEWD----
PWZ36664.1                AAEVVIVVRPPK-DEDD--MVSDEEWD----
XP_016488923.1            LGIVLIVVRPPK-WENED-QLGEEDWD----
XP_016475347.1            LGIVLIVVRPPR-WEDEE-QLGEEDWD----
XP_004249913.1            LGMVLLVVRPPR-WEDED-QQIDED------
KAH0714466.1              LGMVLLVVRPPR-WEDEE-QLIDED------
KAH0711684.1              LGMVLLVVRPPR-WEDEE-QLIDED------
XP_006350959.1            LGMVLLVVRPPR-WEDEE-QLIDED------
EFH61612.1                LGMVVLVVRPPSDDDDDDWQINDEDWD----
XP_002882362.1            LGMVVLVVRPPR-EDDEDWQTSHQNWD----
sp|Q9LKR8|RAF1_ARATH      LGMVVLVVRPPR-DDDDEWQINDEDWD----
XP_020878074.1            LGMVVLVVRPPR-DEDDDWQINDEDWD----
KAG5031773.1              -------------------------------
KAG5045990.1              -------------------------------
KAG5072050.1              LESVFMT------------------------
KAH1203488.1              ---------SPR-------------------
KAH1203487.1              LGSLE--------------GLFYMCWL----
CAN61036.1                LGTVVLVVRPPR-EETDH-ELRDEDWE----
XP_002268548.1            LGTVVLVVRPPR-EETDH-ELRDEDWE----
RVW88115.1                LGTVVLVVRPPR-EETDH-ELRDEDWE----
XP_011465980.1            LGTVVLIVRPPK-DDTEN-ELAEEDWE----
MBA0602665.1              LGTVVLVVRPPK-EESDD-QLSDEDWE----
KJB80888.1                LGTVVLVVRPPK-EESDD-QLSDEDWE----
XP_012463925.1            LGTVVLVVRPPK-EESDD-QLSDEDWE----
XP_007030468.2            LGTVVLVVRPPK-EETDN-QLSDEDWE----
EOY10970.1                LGTVVLVVRPPK-EETDN-QLSDEDWE----
XP_021888657.1            LGTVVLVVRPPK-EEIDD-QLSDEDWE----
XP_002319651.1            LGTVLLVVRPPRYETDD--QLSDEDWE----
XP_002521962.1            LGTVVLVVRPPK-EQTD--QLSDENWE----
XP_021624035.1            LGTVVLVVRPPK-EETDD-QLNDEDWE----
XP_004142574.1            LGTVLLVVRPPRETEDD--QLSDEDWD----
XP_004495565.1            LGNVVLVVRPPR-EDNDD-QLSEEDWD----
XP_003590938.1            LGNVVIVVRPPTENDGD--MLSEEDWD----
AFK41237.1                LGNVVIVVRPPTENDGD--MLSEEDWD----
AGV54807.1                LGTVLLVVRPPK-DENED-QLTDEDWE----
XP_007144004.1            LGTVLLVVRPPK-DENED-QLTDEDWE----
XP_025980010.1            -------------------------------
KAG5004370.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG5152164.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG4997621.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
XP_003536143.1            LGTVLLVVRPPK-EEND--ELSDEDWE----
KAH1191965.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG4908494.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG5075806.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG4919720.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KAG4395437.1              LGTVLLVVRPPK-EEND--ELSDEDWE----
KRH13534.1                IVRPCALTEEPA-GAN---LILDQGDNITVL
XP_006598154.1            DGHVLGLYEPV--------------------
XP_040865419.1            DGHVLGLYEPVARIYLEKVAFPMQS------
KAG5003541.1              -------------------------------
KAG4996767.1              -------------------------------
                                                         
