CLUSTAL multiple sequence alignment by MUSCLE (3.8)


KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
BAC99676.1                ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
sp|Q9SR19|RAF2_ARATH      ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              --------------------------------------------------MSRWPAEHVI
KJB80888.1                MLLWMLIQLMIGPHYFVLTLPPLVLTFCWARVYVAHGPFRLWADSAPTGHMSRWPAEHVI
XP_012463925.1            ------------------------------------------------------------
EOY10970.1                ------------------------------------------------------------
XP_007030468.2            ------------------------------------------------------------
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ------------------------------------------------------------
KAG5152164.1              ------------------------------------------------------------
KAG4997621.1              ------------------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              ------------------------------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
BAC99676.1                ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
sp|Q9SR19|RAF2_ARATH      ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              LSASSLDVCESRSWPSLSSCKLDLRPYLASWVLGSALRDGSASLLCCPLVIRQTLQASKL
KJB80888.1                LSASSLDVCESRSWPSLSSCKLDLRPYLASWVLGSALRDGSASLLCCPLVIRQTLQASKL
XP_012463925.1            ------------------------------------------------------------
EOY10970.1                -------------MGPCTITTVLVGLLSFLNKAQREPIHFSCQIRQPWKALPGLPSPSFL
XP_007030468.2            ------------------------------------------------------------
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ------------------------------------------------------------
KAG5152164.1              ------------------------------------------------------------
KAG4997621.1              ------------------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              ------------------------------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            ---MLSLSHPHPASTGPRHRKPLSTAPQRRRRFSYNIAALILPGGGGGRGSPPNGGKLIL
XP_044969817.1            --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRCTYTIAALILPGGGGPRGSPPNGGKLIL
BAJ84883.1                --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRCTYTIAALILPGGGGPRGSPPNGGKLIL
XP_044449078.1            --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRYTYTIAALILPGGGGPRGSPPNGGKLIL
XP_044322972.1            --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRCTYTIAALILPGGGGPRGSPPNGGKLIL
XP_044395281.1            --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRCTYTIAALILPGGGGPRGSPPNGGKLIL
KAF6988857.1              --MLSVSHPHPAASTGPRHRKPLSTAHHRRRRYTYTIAALILPGGGGPRGSPPNGGKLIL
BAC99676.1                ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            -----------MLSLSHPHPHPASTTAAAAARHHHRRNAPFAPHHRRRRRFAHLTTSAVI
KAB8112826.1              -----------MLSLSHPHPHPASTTAAAAARHHHRRNAPFAPHHRRRRRFAHLTTSAVI
XP_004982996.1            -----------MLSLSHPHTHPAAAP---RHQRAPRPAVAATPASCRRRASHIAASAILL
XP_002448784.1            -----------MLSLSHPHPAAST-----TAPRHQRTPRAATPVWRRRRASHIVASAILL
NP_001140763.1            -----------MLSLSHPHPHPAASTTAPRHQRTAPVWHRRRASHIAASAILLPGGGSTG
XP_016475347.1            -----------MFSLTVNSPKPLSL----STPFLPSHHHPLPSITHKPILNPKPITALII
XP_016488923.1            -----------MFSLTVNSPKPLSL----STPFLPTHPHPLPSITHKPNLNPKPITALII
XP_004249913.1            -----------MFSLTVNSPKSLSL----STPFLPSHPHPIPTITHKPNLSPRPISALII
KAH0714466.1              -----------MFSLTVNSPKPLSL----STPFLPSHPHPLPTITHKPNLTPRPISALII
KAH0711684.1              -----------MFSLTVNSPKPLSL----STPFLPSHPHSLPTITHKPNLTPRPISALII
XP_006350959.1            -----------MFSLTVNSPKPLSL----STPFLPSHPHPLPTITHKPNLTPRPISALII
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------MSIYHFPHHDRVPRLPPH------
KAH1203487.1              ------------------------------------MSIYHFPHHDRVPRLPPH------
XP_020878074.1            -----------MLSLTATTLKSSLFTQSKTHGFSNTRPVYPKPFTTITAALIPASNR---
sp|Q9SR19|RAF2_ARATH      ---------MFSLKSLISSPFTQSTTHGLFTNPITRPVNPLPRTVSFTVTASMIPKRSSA
XP_002882362.1            -------------------MFSLKSSISSPFTQSTTHGLFTNPITRPVNPLPRTVTASMI
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              --------------------------------MGKGYIKRLLDCWVIH------------
CAN61036.1                -----------------------------MLSLNAAASLSLSHHHLLHRRHHHHRLKTHV
XP_002268548.1            -----------------------------MLSLNAPASLSLSHHHLLHRRHHHHRLKTHV
RVW88115.1                -----------------------------MLSLNAAASLSLSHHHLLHRRHHHHRLKTHV
XP_011465980.1            -----------MLSLTSSTLKP-------TFSPFTSTTTFLNPHQPPRLLHPKPSLKPIS
MBA0602665.1              TSIPLCKYSTFINSLTMLSSTSLNPITNPKIPFFSSFSIQNPSLLSFHLPFSPS--KTLL
KJB80888.1                TSIPLCKYSTFINSLTMLSSTSLNPITNPKIPFFSSFSIQNPSLLSFHLPFSPS--KTLL
XP_012463925.1            ----------------MLSSTSLNPITNPKIPFFSSFSIQNPSLLSFHLPFSPS--KTLL
EOY10970.1                LIFCLSIFFLTMLSST--SLKPI--TNP-KNLVFSSFLNQNPSLFSFHPSFPLS--KTLL
XP_007030468.2            ----------------MLSSTSLKPITNPKNLVFSSFLNQNPSLFSFHPSFPLS--KTLL
XP_021888657.1            ---------------------MLSVTTNTFKLIISSPIHSTTNFLTTHQPPSPNLKPSLR
XP_002319651.1            -----------MLSPTLNTHKPLFLSSSNNKPFSSPFLSQQPLFILHLSKTPFKPTKTLS
XP_021624035.1            -----------MFSATVNSLIPISLSNS-SKPFSSSFLSPCLPLFIFQSPFSKTTVKPIS
XP_002521962.1            -----------MLSATVNTHIPISLSNP-NKPFSSSFITPLFTYV------SPSSQKTQL
XP_004142574.1            -----------MLSSTITNANSLSSLSSIAHTTSIFLHQPRDSPLRLFLRRRLNPISAII
XP_004495565.1            ---------MLSLSPCITSVNTPNLKFPNNNGNFFLLPSPSSNHHRPLKPISAIINPSSS
XP_003590938.1            --------------MLSPCISSVNTLNLKFLNIPPSSSNLNRSFYRFKSISAVLNNPSSH
AFK41237.1                --------------MLSPCISSVNTLNLKFLNIPPSSSNLNRSFYRFKSISAVLNSPSSH
XP_007144004.1            ------------MQTLTNMLSLSPSVTANTHTLKPSNPNHLFLITSPSFTNRRHSVKPIS
AGV54807.1                ------------MQTLTNMLSLSPSVTANTHTLKPSNPNHLFLITSPSFTNRRHSVKPIS
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              -----------------------------MRRNHSNSGNYRNPCLTMHQPWASLLVYGI-
KAG5152164.1              -----------------------------MRRNHSNSGNYRNPCLTMHQPWASLLVYGI-
KAG4997621.1              -----------------------------MRRNHSNSGNYRNPCLTMHQPWASLLVYGI-
XP_003536143.1            -----------MLSLSVPPLN--------LKPITPNDLFLSSASPSPHRRYFVKPISAVL
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              --------------------MSSSSISVIQLSFSAQTKSLRYVGIFFFLLGLPSASLLS-
KAG5075806.1              -----------------------------MRRNHSNSGNYRNPCLTMHQPWASLLVYGI-
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ----------MWLDLSDNALEVISSTFGNLSLEYLDLSLIKFEGSTFPEFGAFKSLKTLN
KAG5003541.1              ----------MWLDLSDNALEVISSTFGNLSLEYLDLSLIKFEGSTFREFGAFKSLKTLN
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            PGGG--GGGVGGGGSSGMLPRTPPPSSPG--QLYQPYHPPP--SPLPDTFRNLDLTERLA
XP_044969817.1            PGSG-GGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP--SPLPENYRNLDLTERLA
BAJ84883.1                PGSG-GGGGRGGGVGGGMLPRTPPPTAPPG-QLYQPFHPPP--SPLPENYRNLDLTERLA
XP_044449078.1            PGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP--NPLPETYRNLDLTERLA
XP_044322972.1            PGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP--NPLPETYRNLDLTERLA
XP_044395281.1            PGSG-GGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP--NPLPENYRNLDLTERLA
KAF6988857.1              PGSGGGGGGRGGGGGGGMLPRTPPPTAPPG-QLYQPFHPPP--NPLPETYRNLDLTERLA
BAC99676.1                ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            LGPD--GRPIGGGPRDNKLPFTPPPTAPPD-QLYQPFHPPP--SPLPDKYKDLDLGQRLA
KAB8112826.1              LGPD--GRPIGGGPRDNKLPFTPPPTAPPD-QLYQPFHPPP--SPLPDKYKDLDLGQRLA
XP_004982996.1            PGGG-----STGGRGDRKLPFTPPPMAPPG-QLYQPFHPPP--SPLPSKFRTLDLTQRLE
XP_002448784.1            PGGG--STGGGGGPGDRRLPFTPPPMAPPG-QLYQPFHPPP--SPLPPSLRNLDLTQRLQ
NP_001140763.1            GRGG---------PGDRRLPFTPPPMAPPG-QLYQPFHPPP--SPLPPSLRNLDLSERLQ
XP_016475347.1            PPSS----------------GQQQQYSTQQQQLYQPFRPPP--PPLPPKFRNLDTNAKLE
XP_016488923.1            PPSS--------G-----QQQQYSTQQQQQQQLYQPFRPPP--PLLPPKFRNLDTNSKLE
XP_004249913.1            PPSG---------QRNQQYSTAPPQQQ----QLYQPFRPPP--SPLPPKFRNLDTNSKLE
KAH0714466.1              PPSG---------QRNQQYSTEPPQQQ----QLYQPFRPPP--SPLPPKFRNLDTNSKLE
KAH0711684.1              PPSG---------QRNQQYSTAAPQQQ----QLYQPFRPPP--SPLPPKFRNLDTNSKLE
XP_006350959.1            PPSG-------------QRNQQYSTAAPQQQQLYQPFRPPP--SPLPPKFRHLDTNSKLE
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              -------------------------------------------IPRPPLFSLLTFHG---
KAH1203487.1              -------------------------------------------IPRPPLFSLLTFHG---
XP_020878074.1            -------------------------QAPPQQQLYQPFRPPP--SPIPPKFRSLDTAGRIE
sp|Q9SR19|RAF2_ARATH      NM----------------IPKNPPARQ----QLYQPFRPPS--SPIPTQFRSLDSAGKIE
XP_002882362.1            PKKS----------SANMIPRNPPARQ----QLYQPFRPPS--SPIPTKFRSLDSAGKIE
KAG5031773.1              ---------------------------------------------------MVVLASRIN
KAG5045990.1              -------------------------------------------------------VGRIN
CAN61036.1                KPIS---------ATI--IPSSSTPRHSQQPELYQPFRPPSPNAPIPSHFRSLDTGSRLE
XP_002268548.1            KPIS-----------ATIIPSSSTPRHSQQPELYQPFRPPSPNAPIPSHFRSLDTGSRLE
RVW88115.1                KPIS-----------ATIIPSSSTPRHSQQPELYQPFRPPSPNAPIPSHFRSLDTGSRLE
XP_011465980.1            ASIQ-------------HLPSHPKPNQ----QVYQPFRPPP--SPIPEQYSSLDVNGRLE
MBA0602665.1              KPIS-----------ATLIPSTPPPQQQ---QLYQPFRPPP--SPLPPKFRSLDAQGRLD
KJB80888.1                KPIS-----------ATLIPSTPPPQQQ---QLYQPFRPPP--SPLPPKFRSLDAQGRLD
XP_012463925.1            KPIS-----------ATLIPSTPPPQQQ---QLYQPFRPPP--SPLPPKFRSLDAQGRLD
EOY10970.1                KPIS---------ATL--IPSNPQPQQ--Q-QLYQPFRPPP--SPLPSQFRSLDVAARLE
XP_007030468.2            KPIS-----------ATLIPSNPQPQQQ---QLYQPFRPPP--SPLPSQFRSLDVAARLE
XP_021888657.1            PISA------------TLIPAPTPPSNQQQ-QLYQPFRPPP--SPVPSQFKSLDAAGRLD
XP_002319651.1            VSAT-------------RIPSSPPPYQ----QLYQPFRPPP--SPIPSQYKSLDAPSRLE
XP_021624035.1            ATL---------------IPASPSPSNQ---QLYQPFRPPP--SPIPSQYGSLDTASRLD
XP_002521962.1            KPIS-----------AALIPSTPPPSNQ---QLYQPFRPPP--SPIPSQFSSLDTAGRLE
XP_004142574.1            NPSS--------------------SSLAAKQQVYQPFRPPP--SPLPPQYRSLDTEGKLN
XP_004495565.1            PR-----------QKQQQRQQQQQQQQQPQRQLYQPFRPPP--TSLPPKYGDLDIPARLE
XP_003590938.1            SKKQ--------------RQVQQQQQQQPQKQLYQPFRPPP--TPLPSKYDNLDIPGRID
AFK41237.1                SKKQ--------------RQVQQQQQQQPQKQLYQPFRPPP--TPLPSKYDNLDIPGRID
XP_007144004.1            AIIN--------------PSSFKNPQPPPQQQVYQPFRPPP--EPLPSQYSTLDIAGRID
AGV54807.1                AIIN--------------PSSFKNPQPPPQQQVYQPFRPPP--EPLPSQYSTLDIAGRID
XP_025980010.1            ---------------------------------------------MSNQKSTESCIKNLE
KAG5004370.1              -------------------------------------------KRVEGRSWPAPITGRLW
KAG5152164.1              -------------------------------------------KRVEGRSWPAPITGRLW
KAG4997621.1              -------------------------------------------KRVEGRSWPAPITGRLW
XP_003536143.1            NSSS--------------FKKPEQPLLPQH-QVYQPFRPPP--SPLPSQFGTLDIAGRID
KAH1191965.1              -------------------------------------------------MGTLDIAGRID
KAG4908494.1              --------------------------------------------------GTLDIAGRID
KAG5075806.1              -------------------------------------------KRVEGRSWPAPITGRLW
KAG4919720.1              -----------------------------------------------------MISRRFD
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              LSNN--------------MLVGEVPKELQGLENLQDFQIFN--NHLNASTSGSRHCGESD
KAG5003541.1              LSNN--------------MLVGEVPKELQGLENLQDFQIFN--NHLNASTSGSRHCGESD
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
XP_044969817.1            VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
BAJ84883.1                VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
XP_044449078.1            VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
XP_044322972.1            VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
XP_044395281.1            VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
KAF6988857.1              VLRDRMGRWYEYAPLISSLSREGFTPASIEEATGMSGVEQNRLV----------------
BAC99676.1                -------------------------------------MNQSRGI----------------
EAY78710.1                ----MISTWHEYAPLISALSREGFTPSSIEEATGISGVEQNRVV----------------
XP_015614647.1            VLRDRLGLWHEYAPLISALSREGFTPSSIEEATGISGVEQNSVV----------------
KAB8112826.1              VLRDRLGLWHEYAPLISALSREGFTPSSIEEATGISGVEQNRVV----------------
XP_004982996.1            VLRERLGQWHEYAPLISALSRDGFTPSSIEEATSITGVEQNCLV----------------
XP_002448784.1            ILRDRMGLWHEYAPLIASLSRDGFNPSSIQEATGISGVEQNSLV----------------
NP_001140763.1            ILRDRMGLWHEYAPLISSLSRDGFNPSSIQEATGISGVEQNCLV----------------
XP_016475347.1            VLSNRLGLWYEYAPLIPYLTSEGFTPSTLEEITGLTGVEQNRLV----------------
XP_016488923.1            VLANRLGLWYEYAPLIPSLTREGFTPSTLEEITGLTGVDQNRLV----------------
XP_004249913.1            VLANRLGLWYEYAPLIPSLTSEGFTPSTLEEITGITGVEQNRLV----------------
KAH0714466.1              VLANRLGLWYEYAPLIPSLTSEGFTPSTLEEITGITGVEQNRLV----------------
KAH0711684.1              VLANRLGLWYEYAPLIPSLTSEGFTPSTLEEITGITGVEQNRLV----------------
XP_006350959.1            VLANRLGLWYEYAPLIPSLTSEGFTPSTLEEITGITGVEQNRLV----------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
XP_020878074.1            VLADRLGLWFEYAPLISSLYTEGFIPPSIEELTGLSGVEQNRLI----------------
sp|Q9SR19|RAF2_ARATH      ILAGRMALWFEYAPLISSLYTDGFTPPTIEELTGISSIEQNRLI----------------
XP_002882362.1            ILAGRMALWFEYAPLISSLYTNGFTPPTIEELTGISSIEQNRLI----------------
KAG5031773.1              ILANRLDLWYEYASLISSLIREGFSPSTIEETTDISSIDQNRLI----------------
KAG5045990.1              ILANRLDLWYEYASLSSSLIREGFSPSTIEETTDISSIDQNRLI----------------
CAN61036.1                VLSNRLGLWFEYAPLVSTLMQEGFTPSSLEEATGISGVEQNRLV----------------
XP_002268548.1            VLSNRLGLWFEYAPLVSTLMQEGFTPSSLEEATGISGVEQNRLV----------------
RVW88115.1                VLSNRLGLWFEYAPLVSTLMQEGFTPSSLEEATGISGVEQNRLV----------------
XP_011465980.1            ILANRLGLWYEYAPLIPSLLQQGFTPPTIEEITGISGVEQNRLV----------------
MBA0602665.1              VLANRNGLWFEYAPLIPSLYQEGFSPPSIEEITGITGVEQNRLI----------------
KJB80888.1                VLANRNGLWFEYAPLIPSLYQEGFSPPSIEEITGITGVEQNRLI----------------
XP_012463925.1            VLANRNGLWFEYAPLIPSLYQEGFSPPSIEEITGITGVEQNRLI----------------
EOY10970.1                VLANRGGLWFEYAPLIPSLYQEGFSPPSVEETTGISGVEQNRLI----------------
XP_007030468.2            VLANRGGLWFEYAPLIPSLYQEGFSPPSVEETTGISGVEQNRLI----------------
XP_021888657.1            VLASRLGLWFEYAPLIPSLYQEGFASPSIEEYTGISGVEQNRLV----------------
XP_002319651.1            ILSNRLGLWYEYAPLIPSLFQEGFTPPSIEEATGISGVEQNRLV----------------
XP_021624035.1            ILTNRLGLWYEYALLIPSLIQEGFTPPSIEESTGIPGVEQNRLV----------------
XP_002521962.1            VLANRLGLWYEYAPLIPSLIQEGFSPPSIEESTGISGVEQNRLV----------------
XP_004142574.1            ILSNRLGLWFEYAPLISSLLQEGFTPPVLEEITGISGVQQNSFI----------------
XP_004495565.1            ILANRLGVWHEYAPLITSLIREGFTPPTIEETTGITGVEQNRII----------------
XP_003590938.1            ILANRLGAWHEYAPLITSLLREGFSPPTLEETTGITGVEQNRII----------------
AFK41237.1                ILANRLGAWHEYAPLITSLLREGFSPPTLEETTGITGVEQNRII----------------
XP_007144004.1            ILANRLGLWYQYAPLITSLIREGFSPPTIEETTGITGVEQNRLI----------------
AGV54807.1                ILANRLGLWYQYAPLITSLIREGFSPPTIEETTGITGVEQNRLI----------------
XP_025980010.1            VQVGQLAKQLEDRP--SSSFGANIEKNPKEESKAI--MTRSKMS----------------
KAG5004370.1              IHAASKVPEESTIKAMEYFYKEIYALNGITDIQFPQHYPVSRLL----------------
KAG5152164.1              IHAASKVPEESTIKAMEYFYKEIYALNGITDIQFPQHYPVSRLLGIIPQPRSLLNVNSVQ
KAG4997621.1              IHAASKVPEESTIKAMEYFYKEIYALNGITDIQFPQHYPVSRLL----------------
XP_003536143.1            ILANRLGLWYEYAPLINSLIREGFSPPTIEETTGISGVEQNRLI----------------
KAH1191965.1              VLANRLALWYEYAPLIASLIREGFSPPTIEETTGISGVEQNRLI----------------
KAG4908494.1              VLANRLALWYEYAPLIASLIREGFSPPTIEETTGISGVEQNRLI----------------
KAG5075806.1              IHSASKVPEESTIKAMEYFYKEIYALNGISDIQFPQHYPVSRLL----------------
KAG4919720.1              DKQNR-------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ---------FPLTPWSQTGVHDKNSNSSMEDSDAHKCMLRSHHAS---------------
KAG5003541.1              ---------FPLTPWSQTGVHDKNSNSSMEDSDAHKCMLRSHHAS---------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            -----------VASQVRDSLISDEFP------------------------ADLIHYFDSY
XP_044969817.1            -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
BAJ84883.1                -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
XP_044449078.1            -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
XP_044322972.1            -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
XP_044395281.1            -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
KAF6988857.1              -----------VASQVRDSLISDDFP------------------------DDLLHYFDSY
BAC99676.1                ------------------------------------------------------------
EAY78710.1                -----------VATQVRDSLVADEGG----------------------FPAELLRYFDSY
XP_015614647.1            -----------VATQVRDSLVADEGG----------------------FPAELLRYFDSY
KAB8112826.1              -----------VATQVRDSLVADEGG----------------------FPAELLRYFDSY
XP_004982996.1            -----------VASQVRDSLLSETAA----------------------FPPDLLPYFDSY
XP_002448784.1            -----------VASQVRDSLLDDKVA---------------------AFPPDLLPYFDSY
NP_001140763.1            -----------VASQVRDSLLDDRAA---------------------AFPPDLLPYFDSL
XP_016475347.1            -----------VAAQVRDTLVESAAL-----------------------DEETLSYFES-
XP_016488923.1            -----------VAAQVRDSLVESAAL-----------------------DEETLSYFES-
XP_004249913.1            -----------VAAQVRETLVECGLD------------------------EETLSFFES-
KAH0714466.1              -----------VAAQVLDTLVECGLD------------------------EETLSFFES-
KAH0711684.1              -----------VAAQVRDTLIECGLD------------------------EETLSFFES-
XP_006350959.1            -----------VAAQVRDTLVECGLD------------------------EETLSFFES-
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              -----------------DSLVQSNAD------------------------HDLLTAFEI-
KAH1203487.1              -----------------DSLVQSNAD------------------------HDLLTAFEI-
XP_020878074.1            -----------VGSQVRDSLVQSGAK------------------------PELIAAFDT-
sp|Q9SR19|RAF2_ARATH      -----------VGAQVRDSILQSIHE------------------------PELISAFDT-
XP_002882362.1            -----------VGAQVRDSILQSIHE------------------------PELIAAFDT-
KAG5031773.1              -----------VGAQIR-------------------------------------------
KAG5045990.1              -----------VGAQIR-------------------------------------------
CAN61036.1                -----------VAAQVRHSLLQSSLD------------------------PQILSFFDN-
XP_002268548.1            -----------VAAQVRHSLLQSGLD------------------------PQILSFFDN-
RVW88115.1                -----------VAAQVRHSLLQSSLD------------------------PQILSFFDN-
XP_011465980.1            -----------VAAQVRESLIHSKTD------------------------PEIMAEFDT-
MBA0602665.1              -----------VASQVRESLIQSKTD------------------------EDVMSFFDT-
KJB80888.1                -----------VASQVRESLIQSKTD------------------------EDVMSFFDT-
XP_012463925.1            -----------VASQVRESLIQSKTD------------------------EDVMSFFDT-
EOY10970.1                -----------VAAQVRESLIQSKTD------------------------ENVVSFFDT-
XP_007030468.2            -----------VAAQVRESLIQSKTD------------------------ENVVSFFDT-
XP_021888657.1            -----------VAAQVRESLVQSNTD------------------------PDLVAEFDT-
XP_002319651.1            -----------VGAQVRDSLVQSNTD------------------------PEIVASFDL-
XP_021624035.1            -----------VAAQVRESLVQSNTD------------------------PEIVSAFDT-
XP_002521962.1            -----------VAAKVRESLTQSQTA------------------------AEIVSEFDT-
XP_004142574.1            -----------VGAQVRESLLQSNDS-----------------------DPDVIASFDT-
XP_004495565.1            -----------VATQVRDSLVHSNTD------------------------DQTLSFFDI-
XP_003590938.1            -----------VATQVRDTLVQANTD------------------------EEILSYFDS-
AFK41237.1                -----------VATQVRDTLVQANTD------------------------EEILSYFDS-
XP_007144004.1            -----------VATQVRDSLVQSNAD------------------------PDLLYAFET-
AGV54807.1                -----------VATQVRDSLVQSNAD------------------------PDLLYAFET-
XP_025980010.1            -----------------------NAD------------------------SDLLVAFKT-
KAG5004370.1              -----------GCVEVVGCLTRDELACWEMVPEGVRVEAQTDYCWLCERPQKLLIPFEM-
KAG5152164.1              FIAHQFECLITGCVEVVGCLTRDELACWEMVPEGVRVEAQTDYCWLCERPQKLLIPFEM-
KAG4997621.1              -----------GCVEVVGCLTRDELACWEMVPEGVRVEAQTDYCWLCERPQKLLIPFEM-
XP_003536143.1            -----------VGAQVRDSLVHSKAD------------------------PDLLAAFET-
KAH1191965.1              -----------VGAQVRDSLVQSNAD------------------------PDLLAAFET-
KAG4908494.1              -----------VGAQVRDSLVQSNAD------------------------PDLLAAFET-
KAG5075806.1              -----------GCVEVVGCLTRDELACWEMVPEGVRLEAQTDYCWLCEWPQKLLIPFEM-
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ---------DEENAKIIDSLIQSNAD------------------------SDLLVAFKT-
KAG5003541.1              ---------DEENAKIIDSLIQSNAD------------------------SDLLVAFKT-
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            GGPDLLYELR--------------------------------------------------
XP_044969817.1            GGPDLLYELR--------------------------------------------------
BAJ84883.1                GGPDLLYELR--------------------------------------------------
XP_044449078.1            GGPDLLYELR--------------------------------------------------
XP_044322972.1            GGPDLLYELR--------------------------------------------------
XP_044395281.1            GGPDLLYELR--------------------------------------------------
KAF6988857.1              GGPDLLYELR--------------------------------------------------
BAC99676.1                ------------------------------------------------------------
EAY78710.1                GGPELLYELR--------------------------------------------------
XP_015614647.1            GGPELLYELR--------------------------------------------------
KAB8112826.1              GGPELLYELR--------------------------------------------------
XP_004982996.1            GGPDLLYELR--------------------------------------------------
XP_002448784.1            GGPDLLYELR--------------------------------------------------
NP_001140763.1            GGPEVLYELR--------------------------------------------------
XP_016475347.1            GGAELLYEIR--------------------------------------------------
XP_016488923.1            GGAELLYEIR--------------------------------------------------
XP_004249913.1            GGAELLYEIR--------------------------------------------------
KAH0714466.1              GGAELLYEIR--------------------------------------------------
KAH0711684.1              GGAELLYEIR--------------------------------------------------
XP_006350959.1            GGAELLYEIR--------------------------------------------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              GDAELLYEIR--------------------------------------------------
KAH1203487.1              GDAELLYEIR--------------------------------------------------
XP_020878074.1            GGAELLYEIR--------------------------------------------------
sp|Q9SR19|RAF2_ARATH      GGAELLYEIR--------------------------------------------------
XP_002882362.1            GGAELLYEIR--------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
CAN61036.1                GGDSLLYEIR--------------------------------------------------
XP_002268548.1            GGDSLLYEIR--------------------------------------------------
RVW88115.1                GGDSLLYEIR--------------------------------------------------
XP_011465980.1            GGSELLYEIR--------------------------------------------------
MBA0602665.1              GGAELLYEIR--------------------------------------------------
KJB80888.1                GGAELLYEIR--------------------------------------------------
XP_012463925.1            GGAELLYEIR--------------------------------------------------
EOY10970.1                GGSELLYEIR--------------------------------------------------
XP_007030468.2            GGSELLYEIR--------------------------------------------------
XP_021888657.1            GGAELLYELR--------------------------------------------------
XP_002319651.1            GGAELLYEIR--------------------------------------------------
XP_021624035.1            GGAELLYEIR--------------------------------------------------
XP_002521962.1            GGAELLYEIR--------------------------------------------------
XP_004142574.1            GGAELLYEIR--------------------------------------------------
XP_004495565.1            GGAEILYEIR--------------------------------------------------
XP_003590938.1            GGAEVLYEIR--------------------------------------------------
AFK41237.1                GGAEVLYEIR--------------------------------------------------
XP_007144004.1            SGAELLYEIR--------------------------------------------------
AGV54807.1                SGAELLYEIR--------------------------------------------------
XP_025980010.1            -GAELLYEIR--------------------------------------------------
KAG5004370.1              RGYQGVYNLEKKIYEAAVRGLSPVNSPLPVKFPLPDPQNPFSLKPGSISALTPNLKATEV
KAG5152164.1              RGYQGVYNLEKKIYEAAVRGLSPVNSPLPVKFPLPDPQNPFSLKPGSISALTPNLKATEV
KAG4997621.1              RGYQGVYNLEKKIYEAAVRGLSPVNSPLPVKFPLPDPQNPFSLKPGSISALTPNLKATEV
XP_003536143.1            GGAELLYEIR--------------------------------------------------
KAH1191965.1              GGAELLYEIR--------------------------------------------------
KAG4908494.1              GGAELLYEIR--------------------------------------------------
KAG5075806.1              RGYQGVYNLEKKIYEAAVRGLSPVNSPMPVKFPLPDPRNPFSLKPGSISALTSNLKASEV
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              -GAELLYEIR--------------------------------------------------
KAG5003541.1              -GAELLYEIR--------------------------------------------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            ------------------------------------------------------------
XP_044969817.1            ------------------------------------------------------------
BAJ84883.1                ------------------------------------------------------------
XP_044449078.1            ------------------------------------------------------------
XP_044322972.1            ------------------------------------------------------------
XP_044395281.1            ------------------------------------------------------------
KAF6988857.1              ------------------------------------------------------------
BAC99676.1                ------------------------------------------------------------
EAY78710.1                ------------------------------------------------------------
XP_015614647.1            ------------------------------------------------------------
KAB8112826.1              ------------------------------------------------------------
XP_004982996.1            ------------------------------------------------------------
XP_002448784.1            ------------------------------------------------------------
NP_001140763.1            ------------------------------------------------------------
XP_016475347.1            ------------------------------------------------------------
XP_016488923.1            ------------------------------------------------------------
XP_004249913.1            ------------------------------------------------------------
KAH0714466.1              ------------------------------------------------------------
KAH0711684.1              ------------------------------------------------------------
XP_006350959.1            ------------------------------------------------------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------------------------------------------------------
KAH1203487.1              ------------------------------------------------------------
XP_020878074.1            ------------------------------------------------------------
sp|Q9SR19|RAF2_ARATH      ------------------------------------------------------------
XP_002882362.1            ------------------------------------------------------------
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
CAN61036.1                ------------------------------------------------------------
XP_002268548.1            ------------------------------------------------------------
RVW88115.1                ------------------------------------------------------------
XP_011465980.1            ------------------------------------------------------------
MBA0602665.1              ------------------------------------------------------------
KJB80888.1                ------------------------------------------------------------
XP_012463925.1            ------------------------------------------------------------
EOY10970.1                ------------------------------------------------------------
XP_007030468.2            ------------------------------------------------------------
XP_021888657.1            ------------------------------------------------------------
XP_002319651.1            ------------------------------------------------------------
XP_021624035.1            ------------------------------------------------------------
XP_002521962.1            ------------------------------------------------------------
XP_004142574.1            ------------------------------------------------------------
XP_004495565.1            ------------------------------------------------------------
XP_003590938.1            ------------------------------------------------------------
AFK41237.1                ------------------------------------------------------------
XP_007144004.1            ------------------------------------------------------------
AGV54807.1                ------------------------------------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              DKSSSIS-----------------------------------------------------
KAG5152164.1              DKSSSISLAIAGAQAAATQFSKKDQNSHSTAQNNAPTNMNANNEDTEVATSYNLRSQGRS
KAG4997621.1              DKSSSIS-----------------------------------------------------
XP_003536143.1            ------------------------------------------------------------
KAH1191965.1              ------------------------------------------------------------
KAG4908494.1              ------------------------------------------------------------
KAG5075806.1              DKSSSISLAIAGAQTAATQFSKKDQNSRSTAWNNAPTNMNANNEDTEVARSYNLRSRGRS
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            -------------------F----------------------------------------
XP_044969817.1            -------------------F----------------------------------------
BAJ84883.1                -------------------F----------------------------------------
XP_044449078.1            -------------------F----------------------------------------
XP_044322972.1            -------------------F----------------------------------------
XP_044395281.1            -------------------F----------------------------------------
KAF6988857.1              -------------------F----------------------------------------
BAC99676.1                ------------------------------------------------------------
EAY78710.1                -------------------F----------------------------------------
XP_015614647.1            -------------------F----------------------------------------
KAB8112826.1              -------------------F----------------------------------------
XP_004982996.1            -------------------F----------------------------------------
XP_002448784.1            -------------------F----------------------------------------
NP_001140763.1            -------------------F----------------------------------------
XP_016475347.1            -------------------L----------------------------------------
XP_016488923.1            -------------------L----------------------------------------
XP_004249913.1            -------------------L----------------------------------------
KAH0714466.1              -------------------L----------------------------------------
KAH0711684.1              -------------------L----------------------------------------
XP_006350959.1            -------------------L----------------------------------------
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              -------------------L----------------------------------------
KAH1203487.1              -------------------L----------------------------------------
XP_020878074.1            -------------------L----------------------------------------
sp|Q9SR19|RAF2_ARATH      -------------------L----------------------------------------
XP_002882362.1            -------------------L----------------------------------------
KAG5031773.1              -------------------L----------------------------------------
KAG5045990.1              -------------------L----------------------------------------
CAN61036.1                -------------------L----------------------------------------
XP_002268548.1            -------------------L----------------------------------------
RVW88115.1                -------------------L----------------------------------------
XP_011465980.1            -------------------L----------------------------------------
MBA0602665.1              -------------------L----------------------------------------
KJB80888.1                -------------------L----------------------------------------
XP_012463925.1            -------------------L----------------------------------------
EOY10970.1                -------------------L----------------------------------------
XP_007030468.2            -------------------L----------------------------------------
XP_021888657.1            -------------------L----------------------------------------
XP_002319651.1            -------------------L----------------------------------------
XP_021624035.1            -------------------L----------------------------------------
XP_002521962.1            -------------------L----------------------------------------
XP_004142574.1            -------------------L----------------------------------------
XP_004495565.1            -------------------L----------------------------------------
XP_003590938.1            -------------------L----------------------------------------
AFK41237.1                -------------------L----------------------------------------
XP_007144004.1            -------------------L----------------------------------------
AGV54807.1                -------------------L----------------------------------------
XP_025980010.1            -------------------L----------------------------------------
KAG5004370.1              -------------------L----------------------------------------
KAG5152164.1              MEKGNISSTKLSKTFDDLTLPSYHEEKSSRNRSEGSSKQNRSPGAEADLRQFPQPPSKVS
KAG4997621.1              -------------------L----------------------------------------
XP_003536143.1            -------------------L----------------------------------------
KAH1191965.1              -------------------L----------------------------------------
KAG4908494.1              -------------------L----------------------------------------
KAG5075806.1              NKSEGSSKQNRSPGAEADLM----------------------------------------
KAG4919720.1              ------------------------------------------------------------
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              -------------------L----------------------------------------
KAG5003541.1              -------------------L----------------------------------------
                                                                                      

KAG5148490.1              -----------------MSV-----------------------------AGCINRDIK--
XP_003573987.1            -----------------LNA-----------------RQRVEAAKHAIDRRLEAKGVR--
XP_044969817.1            -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
BAJ84883.1                -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
XP_044449078.1            -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
XP_044322972.1            -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
XP_044395281.1            -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
KAF6988857.1              -----------------LNA-----------------RQRIVATKHTIERRLESKGVR--
BAC99676.1                ------------------------------------------------------------
EAY78710.1                -----------------LNA-----------------RQRADAARHAIDRRLEPRGVR--
XP_015614647.1            -----------------LNA-----------------RQRADAARHAIDRRLEPRGVR--
KAB8112826.1              -----------------LNA-----------------RQRADAARHAIDRRLEPRGVR--
XP_004982996.1            -----------------LNA-----------------RQRADAAKHAIDYRLEPKGVR--
XP_002448784.1            -----------------LNA-----------------RQRADAARHAIDYRLEPKGVR--
NP_001140763.1            -----------------LNA-----------------RQRADAARHAIGYRLEPKGVR--
XP_016475347.1            -----------------LSA-----------------RQRTDAATFLVKNGFDAKQAQ--
XP_016488923.1            -----------------LSA-----------------RQRADAATFLVKNGFDAKQAQ--
XP_004249913.1            -----------------LSG-----------------KQRTDAASFIVRNGFDMKQAQ--
KAH0714466.1              -----------------LSG-----------------KQRVDAARFMVRNGFDMKQTQ--
KAH0711684.1              -----------------LSG-----------------KQRVDAARFMVRNGFDMKQAQ--
XP_006350959.1            -----------------LSV-----------------KQRADAARFMVRNGFDMKQAQ--
KAG4906474.1              ------------------------------------------------------------
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              -----------------LSA-----------------LQHVAATSFLIENRCDGKATQ--
KAH1203487.1              -----------------LSA-----------------LQHVAATSFLIENRCDGKATQ--
XP_020878074.1            -----------------LNT-----------------TQRIAAAEYIVDHDFDTKGAQ--
sp|Q9SR19|RAF2_ARATH      -----------------LST-----------------TQRVAAATFIIDRNIDSKGAQ--
XP_002882362.1            -----------------LST-----------------TQRVAAATFIIDRNIDSKGAQ--
KAG5031773.1              -----------------LSA-----------------SQRMTTAHFLVENRCDGKAPQ--
KAG5045990.1              -----------------LSA-----------------SQRMTTAHFLVENRCDGKAPQ--
CAN61036.1                -----------------LSA-----------------RERLAAARYVAENRVDPRGAQ--
XP_002268548.1            -----------------LSA-----------------RERLAAARYVVENRVDPRGAQ--
RVW88115.1                -----------------LSA-----------------RERLAAARYVAENRVDPRGAQ--
XP_011465980.1            -----------------LSV-----------------QQRAAAARFIVEKKLDAKGAG--
MBA0602665.1              -----------------LSA-----------------SQRAEAVRYIVENGLDAKGAQ--
KJB80888.1                -----------------LSA-----------------SQRAEAVRYIVENGLDAKGAQ--
XP_012463925.1            -----------------LSA-----------------SQRAEAVRYIVENGLDAKGAQ--
EOY10970.1                -----------------LSA-----------------KQRAEAARFILEHGLDPKGAQ--
XP_007030468.2            -----------------LSA-----------------KQRAEAARFILEHGLDPKGAQ--
XP_021888657.1            -----------------LSA-----------------AQRAAAARFIIENRFDAKGAQ--
XP_002319651.1            -----------------LSA-----------------TQRSAAARFIVVNKMDTKGAQ--
XP_021624035.1            -----------------LSA-----------------TQRNAAARFIVEHKLDAKGAQ--
XP_002521962.1            -----------------LSA-----------------PQRAAAARFIVENRLDAKGAE--
XP_004142574.1            -----------------LST-----------------EKRAAAAKYIVENRLDSKGAQ--
XP_004495565.1            -----------------LST-----------------SQRASVARFIVENRFDGKGAQ--
XP_003590938.1            -----------------LST-----------------SQRAAAARFIVEKRYDGKGAQ--
AFK41237.1                -----------------LST-----------------SQRAAAARFIVEKRYDGKGAQ--
XP_007144004.1            -----------------LST-----------------SQRVAAARFLVENNCDGKAAQ--
AGV54807.1                -----------------LST-----------------SQRVAAARFLVENNCDGKGGA--
XP_025980010.1            -----------------LSA-----------------FQCITVARFLVENRCDGKATQ--
KAG5004370.1              -----------------AIA-----------------GAQAAATQFSKKDQNSHSTAQNN
KAG5152164.1              LSENGVFIRECERISVALDGEKDGYPFFILGKDEGSASQRVAAARFLVENRCDGKAAQ--
KAG4997621.1              -----------------AIA-----------------GAQAAATQFSKKDQNSHSTAQNN
XP_003536143.1            -----------------LSA-----------------SQRVAAARFLVENRCDGKAAQ--
KAH1191965.1              -----------------LSA-----------------SQRVAAARFLVENRCDGKAAQ--
KAG4908494.1              -----------------LSA-----------------SQRVAAARFLVENRCDGKAAQ--
KAG5075806.1              -----------------ISRRFDDKQNRSPAPLRDPPPQRVAAARFLVENRCDGKAAQ--
KAG4919720.1              -----------------SPG-----------------AERVAAARFLVENRCDGKAAQ--
KAG4395437.1              ------------------------------------------------------------
KRH13534.1                ------------------------------------------------------------
XP_006598154.1            ------------------------------------------------------------
XP_040865419.1            ------------------------------------------------------------
KAG4996767.1              -----------------LSA-----------------FQCITVARFLVENRCDGKATQ--
KAG5003541.1              -----------------LSA-----------------FQCITVARFLVENRCDGKATQ--
                                                                                      

KAG5148490.1              ----------------GMRLLPSRVH-HLGMWYT--------------------------
XP_003573987.1            ------------ELARSMKDFPQRRG-DDG-WDAF-DRHSAGDCLAYARFRLSREA----
XP_044969817.1            ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
BAJ84883.1                ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
XP_044449078.1            ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
XP_044322972.1            ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
XP_044395281.1            ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
KAF6988857.1              ------------ELARSMKDFPQRRG-DEG-WDAF-DRHSAGDCLAYARFRLSREA----
BAC99676.1                ------------DLKKTFQEI----------WPHS------GEAI---------------
EAY78710.1                ------------ELARSMKDFPQRRG-DDG-WEAF-TRDNPGDCLAFARFRQSREA----
XP_015614647.1            ------------ELARSMKDFPQRRG-DDG-WEAF-TRDNPGDCLAFARFRQSREA----
KAB8112826.1              ------------ELARSMKDFPQRRG-DDG-WEAF-TRDNPGDCLAFARFRQSREA----
XP_004982996.1            ------------ELARSMKDFPRRRAVDEG-WEAF-DGASPGDCLAFARFRQSREA----
XP_002448784.1            ------------ELARAMKGFPRWRG-EEG-WEAF-GRDSPADCLAYARFRQSREA----
NP_001140763.1            ------------ELARAMKGFPRWRG-EEG-WEAF-SKDSPADCLAFARFRQSREA----
XP_016475347.1            ------------DLARAIKDYPRRRV-DYG-WDKF-NGDSPGDCLAFMYFRLAQEYAAA-
XP_016488923.1            ------------DLARAIKDYPRRRV-EYG-WDKF-HGDSPGDCLAFMYFRLAQEYAAA-
XP_004249913.1            ------------DLARSMKDFPRRRI-DYG-WDKF-TGDSPGDCLAFWFFRLAQEHAAA-
KAH0714466.1              ------------DLARAMKDFPRRRI-DYG-WDKF-TGDSPGDCLAFWFFRLAQEHAAA-
KAH0711684.1              ------------DLARAMKDFPRRRI-DYG-WDKF-TGDSPGDCLAFWFFRLAQEHAAA-
XP_006350959.1            ------------DLARAMKDFPRRRI-DYG-WDKF-TGDSPGDCLAFWFFRLAQEHAAA-
KAG4906474.1              -------------------------------MKDL------GD---------SKEYR---
EFH61612.1                -------------------------------MSYRYNLAVSGD-----------------
KAG5054963.1              ------------------------------------------------------------
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              ------------ELAHAMKAFP-----NKG-WESF-DYTLPEDCLSF-------------
KAH1203487.1              ------------ELAHAMKAFP-----NKG-WESF-DYTLPEDCLSF-------------
XP_020878074.1            ------------DLARAIKDYPHRRG-DVG-WEDF-DYNLPGDCLSFMLYRKSREYR---
sp|Q9SR19|RAF2_ARATH      ------------DLARAIKDYPNRRG-DVG-WLDF-DYNLPGDCLSFLYYRQSRENK---
XP_002882362.1            ------------DLARAIKDYPNRRG-DVG-WLDF-DYNLPGDCLSFLYYRQSRENK---
KAG5031773.1              ------------ELAPSVKDFPSRRE-DKGLWNG--ERGGYGGC------RGC-------
KAG5045990.1              ------------ELAPSVKDFPSRRE-DKGLWNG--ERGGYGGC------RGC-------
CAN61036.1                ------------ELARAIKDFPRRRG-DRG-WECF-DYNVPGDCLAFMYYRQSREHR---
XP_002268548.1            ------------ELARAIKDFPRRRG-DRG-WECF-DYNVPGDCLAFMYYRQSREHR---
RVW88115.1                ------------ELARAIKDFPRRRG-DRG-WECF-DYNVPGDCLAFMYYRQSREHR---
XP_011465980.1            ------------DLARATKDFPRRRG-DKG-WESF-DYTNPGDCLAFMYYRQAREHN---
MBA0602665.1              ------------DLARAMKDFPRRKM-DKG-WKSF-EYGLPGDCLSFMYYRLSREHG---
KJB80888.1                ------------DLARAMKDFPRRKM-DKG-WKSF-EYGLPGDCLSFMYYRLSREHG---
XP_012463925.1            ------------DLARAMKDFPRRKM-DKG-WKSF-EYGLPGDCLSFMYYRLSREHG---
EOY10970.1                ------------DLARAMKDFARRKT-DKG-WKSF-DYQLPGDCLSFMYYRQSREHK---
XP_007030468.2            ------------DLARAMKDFARRKT-DKG-WKSF-DYQLPGDCLSFMYYRQSREHK---
XP_021888657.1            ------------DLARAMKDYPRRRG-DRG-WDFF-DYSLPGDCLSFMYYRQSREHQ---
XP_002319651.1            ------------DLARAMKDFPRRRG-DKF-WESF-DYVLPGDCLSFMYYRQSREHK---
XP_021624035.1            ------------DLARAMKDYPRRRG-EKA-WESF-DYNLPGDCLSFMYYRQAREHN---
XP_002521962.1            ------------DLARAMKDFPRRRG-DKG-WESF-DYTLPGDCLSFMYYRQSREHK---
XP_004142574.1            ------------DLARAMKDFPRRRG-DKG-WEYF-DYDFAGDCLAYMYYRLSREYN---
XP_004495565.1            ------------DIARSIKDFPKRRG-EKG-WESF-DYTLPGDCLSYMYYRQSREHT---
XP_003590938.1            ------------DLARSIKDFPSRRG-EKH-WESF-DYHLPGDCLAYLYYRQSKENK---
AFK41237.1                ------------DLARSIKDFPSRRG-EKH-WESF-DYHLPGDCLAYLYYRQSKENK---
XP_007144004.1            ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQGREHK---
AGV54807.1                ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQGREHK---
XP_025980010.1            ------------ELARAMKDFPSRHG-DKG-WESF-DYTLLEDCLSFMYYRQSREHR---
KAG5004370.1              APTNMNANNEYTEVATSYNLRSQGRSMEKGNISST-KLSKTFDDLTLPSYHEEKSSRNRS
KAG5152164.1              ------------ELARSMKDFPSRRG-DKG-WARF-DYTLPGDCLSFMYYRQSREHR---
KAG4997621.1              APTNMNANNEDTEVATSYNLRSQGRSMEKGNISST-KLSKTFDDLTLPSYHEEKSSRNRS
XP_003536143.1            ------------ELARSMKDFPSRRG-DKG-WARF-DYTLPGDCLSFMYYRQSREHR---
KAH1191965.1              ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQSKEHR---
KAG4908494.1              ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQSKEHR---
KAG5075806.1              ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQSKEHR---
KAG4919720.1              ------------ELARAMKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQSKEHR---
KAG4395437.1              -----------------MKDFPSRRG-DKG-WESF-DYTLPGDCLSFMYYRQSKEHR---
KRH13534.1                -----------------MKDFPSKRG-DKG-WESF-DYTLERDCLSFMYYWQSREHR---
XP_006598154.1            -----------------MKDFPSKRG-DKG-WESF-DYTLERDCLSFMYYWQSREHR---
XP_040865419.1            -----------------MKDFPSKRG-DKG-WESF-DYTLERDCLSFMYYWQSREHR---
KAG4996767.1              ------------ELARAMKDFPSRHG-DKG-WESF-DYTLLEDCLSFMYYRQSREHR---
KAG5003541.1              ------------ELARAMKDFPSRHG-DKG-WESF-DYTLLEDCLSFMYYRQSREHR---
                                                                                      

KAG5148490.1              ----------------------------------------RRLIFLAGARIKDCGMVK--
XP_003573987.1            -----------------------------------IANEDRMPELERSLDVVETETARAR
XP_044969817.1            -----------------------------------IANEDRIPELERSLDVVETESARAR
BAJ84883.1                -----------------------------------IANEDRIPELERSLDVVETESARAR
XP_044449078.1            -----------------------------------IANEDRIPELERSLDVVETESARAR
XP_044322972.1            -----------------------------------IANEDRIPELERSLDVVETESARAR
XP_044395281.1            -----------------------------------IANEDRIPELERSLDVVETESARAR
KAF6988857.1              -----------------------------------IANEDRIPELERSLDVVETESARAR
BAC99676.1                ------------------------------------DAEDSVAELERALEVVDT------
EAY78710.1                -----------------------------------IDAEDSVAELERALEVVDTEPARAR
XP_015614647.1            -----------------------------------IDAEDSVAELERALEVVDTEPARAR
KAB8112826.1              -----------------------------------IDAEDSVAELERALEVVDTEPARAR
XP_004982996.1            -----------------------------------IDVDDRIAELNRALQVVATETARAR
XP_002448784.1            -----------------------------------IDVEERIAELERALQVVETESGRAR
NP_001140763.1            -----------------------------------IDVQDRVAELERALQVVETESGRAR
XP_016475347.1            -----------------------------------ASEDLRRSSMEKALEVVESESARNL
XP_016488923.1            -----------------------------------ASEDLRRSSMEKALEVAESESARNL
XP_004249913.1            -----------------------------------AAEDSRVEAMEKALEVVETESARNV
KAH0714466.1              -----------------------------------AAEDSRVEAMEKALEVVDTESARNV
KAH0711684.1              -----------------------------------AAEESRVEAMEKALEVVETESARNV
XP_006350959.1            -----------------------------------AAEESRVEAMEKALEVVETESARNV
KAG4906474.1              -----------------------------------NPSEQRTLALEQALGVAETKAEANV
EFH61612.1                ------------------------------------------------------------
KAG5054963.1              --------------------------------------------------MAETKATTNV
KAG5126716.1              --------------------------------------------------MVETEATRNV
KAH1203488.1              -----------------------------------EPVGAEDSALEQALGVAETKAVTNV
KAH1203487.1              -----------------------------------EPVGAEDSALEQALGVAETKAVTNV
XP_020878074.1            -----------------------------------SPSEIRTTLLEQALETAVTEKAKKA
sp|Q9SR19|RAF2_ARATH      -----------------------------------NPSDQRTSMLLQALGVAESEKAKNR
XP_002882362.1            -----------------------------------NPSEQRTSMLLQALGVVESEKAKNK
KAG5031773.1              ------------------------------------------------------------
KAG5045990.1              ------------------------------------------------------------
CAN61036.1                -----------------------------------NSLDKRRAALEKALEVAETEKAKRV
XP_002268548.1            -----------------------------------NSLDKRRAALEKALEVAETEKAKRV
RVW88115.1                -----------------------------------NSLDKRRAALEKALEVAETEKAKRV
XP_011465980.1            -----------------------------------DMSETRTDALEEALKVVGSEKARSV
MBA0602665.1              -----------------------------------NPSEQRTAALMQALQVAESESAKKE
KJB80888.1                -----------------------------------NPSEQRTAALMQALQVAESESAKKE
XP_012463925.1            -----------------------------------NPSEQRTAALMQALQVAESESAKKE
EOY10970.1                -----------------------------------NPSEQRTSALRQALKVAESESAKKE
XP_007030468.2            -----------------------------------NPSEQRTSALRQALKVAESESAKKE
XP_021888657.1            -----------------------------------NPSSERTAALQQALEVAESEKAKGE
XP_002319651.1            -----------------------------------NPSESRTNALQMALEVAESEKAKSA
XP_021624035.1            -----------------------------------NPSELRTNTLEMAMDVAESEKAKSA
XP_002521962.1            -----------------------------------TPSEPRTNALERALDVAESEKAKNE
XP_004142574.1            -----------------------------------SSTERRTAALEEALKVVVTEKARDL
XP_004495565.1            -----------------------------------NPSDQRTAALELALSVVQSEKAKKV
XP_003590938.1            -----------------------------------NPSDPRTAFLQQALSAVESDKARNV
AFK41237.1                -----------------------------------NPSDPRTAFLQQALSAVESDKARNV
XP_007144004.1            -----------------------------------NPSDQRSSALEQALRVAETEKARKV
AGV54807.1                -----------------------------------NPSDQRSSALEQALRVAETEKARKV
XP_025980010.1            -----------------------------------NPSKQRTSVLE--------------
KAG5004370.1              EGSSKQNRSPGAEADLRQFPQPPSKVSLSENGVFMNPSEQRTSALEQALRVAETEAARNM
KAG5152164.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNM
KAG4997621.1              EGSSKQNRSPGAEADLRQFPQPPSKVSLSENGVFMNPSEQRTSALEQALRVAETEAARNM
XP_003536143.1            -----------------------------------NPSEQRTSALEQALRVAETEAARNM
KAH1191965.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNV
KAG4908494.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNV
KAG5075806.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNV
KAG4919720.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNV
KAG4395437.1              -----------------------------------NPSEQRTSALEQALRVAETEAARNV
KRH13534.1                -----------------------------------NPSEQRTSALEQGLGVAEMEAARNV
XP_006598154.1            -----------------------------------NPSEQRTSALEQGLGVAEMEAARNV
XP_040865419.1            -----------------------------------NPSEQRTSALEQGLGVAEMEAARNV
KAG4996767.1              -----------------------------------NPSKQRTSVLE--------------
KAG5003541.1              -----------------------------------NPSKQRTSVLE--------------
                                                                                      

KAG5148490.1              -----EGDTVDAGG-----------------AACVPVVRLRIGEVAEANSVVVLPVSVTD
XP_003573987.1            VELEMERAIRKAAG---EEVEEPEADVNA--RPAVPVVRLIYGEISEASIVLLLPVVRET
XP_044969817.1            VELEMERAIKKAAG---EEVEELEAKVDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
BAJ84883.1                VELEVERAIKKAAG---EEVEELEAKVDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
XP_044449078.1            VELEIERAIKKAAG---EEVEELEAEIDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
XP_044322972.1            VELEIERAIKKAAG---EEVEELEAEIDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
XP_044395281.1            VELEIEKAIKKAAG---EEVEELEAEVDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
KAF6988857.1              VELEIEKAIKKAAG---EEVEELEAEVDA--RPAVPVVRLMYGEISEASIVLLLPVVKET
BAC99676.1                --------------------------------------------------VLLLPVGREG
EAY78710.1                VEAELDRARRKAAGEEVDDEDGAANAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREG
XP_015614647.1            VEAELDRARRKAAGEEVDDEDGAANAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREG
KAB8112826.1              VEAELDRARRKAAGEEVDDEDGAANAAAAASRPAVPVVRLMYGEVAEATTVLLLPVVREG
XP_004982996.1            LELEMERARKKAAG---EEVEEGEDDTAS--RPAVNVVRLQYGEVAEASTVLLLPVVRET
XP_002448784.1            VELELERARKKAAGEEVVEEDDPAAS-----RPNVTVVRLQYGEVAEATTVFMLPVVRET
NP_001140763.1            VELELERARRKAAGEEEVDEEGEEDDAAASLRPGVTVVRLRYGEVAEATTVILLPVVRET
XP_016475347.1            LVMELEGREVAKES----VLDD---------GVTVPLVRMKLGEVAESTIVVVLPVCKAE
XP_016488923.1            LVMELEGNEVAKES----VKDD---------GVTVPLVRMKLGEVAESTIVVVLPVCKAE
XP_004249913.1            LVEVLEGKGVDKES----VIDE---------QVKVPLVRMKLGEVAESTKVVVLPVCKAE
KAH0714466.1              LVEVLEGKGVDKDS----VIDE---------QVKVPLVRMKLGEVAESTKVVVLPVCKAE
KAH0711684.1              LVEVLEGKGVDKDS----VIDE---------QVKVPLVRMKLGEVAESTKVVVLPVCKAE
XP_006350959.1            LVEVLEGKGVDKDS----VIDE---------QVKVPLVRMKLGEVAESTKVVVLPVCKAE
KAG4906474.1              ILEGLGGKGEEGDK-----VGEGEA------AARVPVVRLRIGEVAETSSMVLLPISAKE
EFH61612.1                ---------------------------------RQPIVISQY------------------
KAG5054963.1              ILEELEGKGEEGDT-----VGEGEA------ATRVPVVRLRIGEVAKVSSMVLLSVFATE
KAG5126716.1              ILEELEGKGEEGDT-----VGEREV------AASVPMVMLRIGEVAEASLVVLLPVSAVE
KAH1203488.1              ILEELEGKGEEGDT-----VGEREA------AAHVPVVRLRIGEVAEVSSVVLLPVFATE
KAH1203487.1              ILEELEGKGEEGDT-----VGEREA------AAHVPVVRLRIGEVAEVSSVVLLPVFATE
XP_020878074.1            VTRELHGESEEERA----KEEEIK-------IIRVPVVRLRFGEVAGASSVVVLPVCKAE
sp|Q9SR19|RAF2_ARATH      LNTELYGDKEAEKEKEKKKKEEEVK------AIRIPVVRLKFGEVAEATSVVVLPVCKAE
XP_002882362.1            LNKELYGEKEEEKEKEKKKKEEEVK------AIRIPVVRLKFGEVAGASSVVVLPVCKAE
KAG5031773.1              --------------------------------------------------------CMCS
KAG5045990.1              --------------------------------------------------------CMCS
CAN61036.1                LLEELERNDDADDG----K-SEIEE------AVRVPVVRMKTGEVAEATT----------
XP_002268548.1            LLEELERNDDADDG----K-SEIEG------AVRVPVVRMKTGEVAEATTVVVLPVCEAQ
RVW88115.1                LLEELERNDDADDG-----KSEIEE------AVRVPVVRMKTGEVAEATTVVVLPVCEAQ
XP_011465980.1            IVRELEGASVRDEE------EEVVA------VVKVPVVRLKFGEVGESSRVVVLPVCKAE
MBA0602665.1              VSEELEGGEDEKPE----KDDDLEY------RVRVPVVRMQFGEVAEATSVVVLPVCMAE
KJB80888.1                VSEELEGGEDEKPE----KDDDLEY------RVRVPVVRMQFGEVAEATSVVVLPVCMAE
XP_012463925.1            VSEELEGGEDEKPE----KDDDLEY------RVRVPVVRMQFGEVAEATSVVVLPVCMAE
EOY10970.1                LLEELECGEDGKEE----KEEDLDY------GVRVPVVRLKIGEVAEASSVVVLPVCKAE
XP_007030468.2            LLEELECGEDGKEE----KEEDLDY------GVRVPVVRLKIGEVAEASSVVVLPVCKAE
XP_021888657.1            VSRELEGDSEKKGG----KEDGVEG------TVRVPVVRMKIGEVAEASSVVVLPVCRAE
XP_002319651.1            ILKELEGGGERKER----AEGETAD------GVRVPVVRLKIGEVAEATSVVVLPVCRSE
XP_021624035.1            VLGELKREGEGEDA----KEEETGD------GVRVPVVRLRIGEVAEATRVVVLPVCKAE
XP_002521962.1            VLKELEGDSEGKEE----KEGEVGD------ATRVPVVRLRIGEVAEATSVVVLPVCRAL
XP_004142574.1            IVGDLEGKGDGKDG----VEEEIGA------AVKVPVVRMKIGEVAEATTVVVMPVCKAG
XP_004495565.1            ILEELEGKVES-------VVEDVVI------KVSVPVVRLKIGEVAESSSVIVLPVVKAE
XP_003590938.1            ILEELNGKAEEE------KVEDVVL------KVPVNVVRLKIGEVAEATSVVVLPVCKAE
AFK41237.1                ILEELSGKAEEE------KVEDVVL------KVPVNVVRLKIGEVAEATSVVVLPVCKAE
XP_007144004.1            VLEELEGNEEED------KVEDGE-------RVRVPVVRLRIGEVAEASSVVVLPVCGAE
AGV54807.1                VLEELEGNEEED------KVEDGE-------RVRVPVVRLRIGEVAEASSVVVLPVCGAE
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ILEELEGNGEEGDK-----VDAGEG------AVRVPVVRLRIGEVAEASSVVVLPVSAAE
KAG5152164.1              ILEELEGNGEEGDK-----VDAGEG------AVRVPVVRLRIGEVAEASSVVVLPVSAAE
KAG4997621.1              ILEELEGNGEEGDK-----VDAGEG------AVRVPVVRLRIGEVAEASSVVVLPVSAAE
XP_003536143.1            ILEELEGNGEEGDK-----VDAGEG------AVRVPVVRLRIGEVAEASSVVVLPVSAAE
KAH1191965.1              ILEELEGKGEEGDT-----VGEGEA------AARVPVVRLRIGEVAEASSVVLLPVSAAE
KAG4908494.1              ILEELEGKGEEGDT-----VGEGEA------AARVPVVRLRIGEVAEASSVVLLPVSAAE
KAG5075806.1              ILEELEGKGEEGDT-----VGEGEA------AARVPVVRLRIGEVAEASSVVLLPVSAAE
KAG4919720.1              ILEELEGKGEEGDT-----VGEGEA------AARVPVVRLRIGEVAEASSVVLLPVSAAE
KAG4395437.1              ILEELEGKGEEGDT-----VGEGEA------AARVPVVRLRIGEVAEASSVVLLPVSAAE
KRH13534.1                ILEELEGKGVSEKK-----------------------IQKQTVSLMAASFRWILQLHKD-
XP_006598154.1            ILEELEGKGVSEKK-----------------------IQKQTVSLMAASFRWILQLHKD-
XP_040865419.1            ILEELEGKGVSEKK-----------------------IQKQTVSLMAASFRWILQLHKD-
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ER----------------------------------------------------------
XP_003573987.1            DGVEAVDLAPRRKKTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIQL
XP_044969817.1            DGVQAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
BAJ84883.1                DGVQAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
XP_044449078.1            DGVKAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
XP_044322972.1            DGVKAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
XP_044395281.1            DGVKAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
KAF6988857.1              DGVKAVDLAPRRSQTD--ADL---GIVEVDKGW--ARWAVLPGWAPVMAVADEA-VVIEL
BAC99676.1                DET---------------------------------------------------------
EAY78710.1                DGGEALAHAPRRTRTD--ADL---GMVEVDKGW--TRWAVVPGWGPVAEVAGEA-VVIEL
XP_015614647.1            DGGEALAHAPRRTRTD--ADL---GMVEVDKGW--TRWAVVPGWGPVAEVAGEA-VVIEL
KAB8112826.1              DGGEALAHAPRRTRTD--ADL---GMVEVDKGW--TRWAVVPGWGPVAEVAGEA-VVIEL
XP_004982996.1            DGVAAMESAPRRTKTD--VDL---GIVEVDKAW--ARWAVVPGWGPVAAAAEEA-VAIEL
XP_002448784.1            DGVAAMESAPRRTKTD--VDL---GIVEVDKAW--ARWAVLPGWGPVAEAADDA-VVVEL
NP_001140763.1            DGVAAMESAPRRAKTD--VGL---GVVEVDRAW--ARWAVVPGWGPVAEAADDA-VVVEL
XP_016475347.1            GRDVEVEAAPWECGGV--GDF---GIVEAEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
XP_016488923.1            GRDVEVEAAPWECGGV--GDF---GIVEAEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
XP_004249913.1            KREFEVEAAPWECGGV--GEF---GVVEAEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
KAH0714466.1              KREFEVEAAPWECDGV--GDF---GIVEVEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
KAH0711684.1              KREFEVEAAPWECGGV--GDF---GVVEAEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
XP_006350959.1            KREFEVEAAPWECGGV--GDF---GVVEAEKDW--RRWVVLPGWQPIAGLERGG-VAVSF
KAG4906474.1              EKK--ILEACRRRIEDRLGKF---SLIQLSEEH-------------PNGMRR---VVKSL
EFH61612.1                --------------QT--NHF---GV----------------------------------
KAG5054963.1              EKE--ILEACIIRY------L---LHVMSVATP--TKDCLKLGREL--------------
KAG5126716.1              ERE--ILEACKICL----------------------------------------------
KAH1203488.1              EKE--ILEACKISSKE-------------------TYILLIPL-----------------
KAH1203487.1              EKE--ILEACKIRLYD--LRLLQRGVVQCYEGHVNSHTHMQISVDPSERFVMSG-----G
XP_020878074.1            EGEEKLLEAPMEFESG--GEF---GVVEAEKDW--SRWVVLPGWEPVVAVRKGG-VAVSF
sp|Q9SR19|RAF2_ARATH      EGEKKILEAPMEIIAG--GDF---KVVEAEKGW--KRWVVLPSWNPVAAIGKGG-VAVSF
XP_002882362.1            EGEKKILEAPMEIIAG--GDF---KVVEAEKGW--KRWVVLPGWNPVAAIGKGG-VAVSF
KAG5031773.1              GGE--------------------------AKDW-------------------GG------
KAG5045990.1              GGE--------------------------AKDW-------------------GG------
CAN61036.1                --VSGITGAPLECRSQ--GEF---GVVVAEKGW--KRWVVLPGWEPVAGLRAG--VVVAF
XP_002268548.1            EGVDVVLGAPLECRSQ--GEF---GVVVAEKGW--KRWVVLPGWEPVAGLRAG--VVVAF
RVW88115.1                EGVDVVLGAPLECRSQ--GEF---GVVVAEKGW--KRWVVLPGWEPVAGLRAG--VVVAF
XP_011465980.1            EKDKEVMEAPWECESE--GEL---GVVVAEKGW--KRWVVLPGWEPVVGLGKGG-VVVSF
MBA0602665.1              EDTKELLEAPLECRSG--GDF---GVVEAEKGW--KRWVVLPSWEPLAGLRHGG-VVVAF
KJB80888.1                EDTKELLEAPLECRSG--GDF---GVVEAEKGW--KRWVVLPSWEPLAGLRHGG-VVVAF
XP_012463925.1            EDTKELLEAPLECRSG--GDF---GVVEAEKGW--KRWVVLPSWEPLAGLRHGG-VVVAF
EOY10970.1                EKDREILQAPLECRSK--GDF---GVVEAEKGW--NRWVVLPGWEPVVGLSNGG-VVVAF
XP_007030468.2            EKDREILQAPLECRSK--GDF---GVVEAEKGW--NRWVVLPGWEPVVGLSNGG-VVVAF
XP_021888657.1            ESEAELLEVPWECKSK--GEF---GVVVSEKGW--KRWVVLPGWEPVAGLGNGG-VVVAF
XP_002319651.1            DGERKIVEAPWECKGQ--GEF---GVVVAEKAW--ERWVVLPGWEPVLGLGRGG-VAVAF
XP_021624035.1            EREREILEAPWECRTE--GEF---GVVAAEKGW--KRWVVLPSWEPLVGLEKGG-VVVAF
XP_002521962.1            QKEKEIWEAPWECKSE--GEF---GVVVAEKGW--ERWVVLPGWEPVVGLEKGG-VVVAF
XP_004142574.1            EGEKGVGEAPMEVRSE--GEF---GVVVAEKGW--SRWVVLPGWEPVAGLVKGGGVVVAF
XP_004495565.1            EGDKVILEAPSEMRNE--GVF---GVVVAEKGW--ERWVVLPSWDPIVNLGKGG-VVVSF
XP_003590938.1            EGERVIMEAPSEIRKE--GEF---GIVVAEKGW--EKWVVLPAWGPVVNLGKG--VVVSF
AFK41237.1                EGERVIMETPSEIRKE--GEF---GIVVAEKGW--EKWVVLPAWGPVVNLGKG--VVVSF
XP_007144004.1            EKE--VLEAPFECRSE--GEF---GVVVAEKGW--ARWVVLPWWEPVVGLIKGG-VVVSF
AGV54807.1                EKE--VLEAPFECRSE--GEF---GVVVAEKGW--ARWVVLPWWEPVVGLIKGG-VVVSF
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              ERE--ILEAPYESRSQ--GVF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG5152164.1              ERE--ILEAPYESRSQ--GVF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG4997621.1              ERE--ILEAPYESRSQ--GVF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
XP_003536143.1            ERE--ILEAPYESRSQ--GVF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAH1191965.1              ERE--ILEAPFESRSQ--GEF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG4908494.1              ERE--ILEAPFESRSQ--GEF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG5075806.1              ERE--ILEAPFESRSQ--GEF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG4919720.1              ERE--ILEAPFESRSQ--GEF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KAG4395437.1              ERE--ILEAPFESRSQ--GEF---GVVVAEKGW--GKWVVLPSWDPVVGLGKGG-VVVSF
KRH13534.1                -----VPKAARFYSEG--LDF---SINVCSLRW--------------AELQSGS-LKVAL
XP_006598154.1            -----VPKAARFYSEG--LDF---SINVCSLRW--------------AELQSGS-LKVAL
XP_040865419.1            -----VPKAARFYSEG--LDF---SINVCSLRW--------------AELQSGS-LKVAL
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ------------------------------------------------------------
XP_003573987.1            ADGR-VLPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
XP_044969817.1            ADGR-VLPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
BAJ84883.1                ADGR-VLPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
XP_044449078.1            ADGR-VLPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
XP_044322972.1            ADGR-VLPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
XP_044395281.1            ADGR-VMPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
KAF6988857.1              ADGR-VMPWRS----AENERVLVVADRKRKEV-VDEGIYVLEKG---------GKLVVER
BAC99676.1                ------------------ERVLVVANRGRREV-VEDGIYVVDSE---------GRLVVEK
EAY78710.1                ADGR-TLPWRS----AEAERVLVVANRGRREV-VEDGIYVVERE---------GRLVVEK
XP_015614647.1            ADGR-TLPWRS----AEAERVLVVANRGRREV-VEDGIYVVERE---------GRLVVEK
KAB8112826.1              ADGR-TLPWRS----AEAERVLVVANRGRREV-VEDGIYVVERE---------GRLVVEK
XP_004982996.1            ADGR-RLPWRT----AEEEPVLVIANRGQKEV-AEQGSYVLEKE---------GRLVVER
XP_002448784.1            ADGR-RLPWRT----ADEEPVLVIANRSKKEV-VEQGIYVLEKD---------GRLVVER
NP_001140763.1            ADGR-RLPWRM----SDEEPVLVIANRSKKEV-VEEGVYVLERE---------GRLVVER
XP_016475347.1            KSGN-FLPWRE-KSKYKQEPVLVVADRGRTEVASEDG-FYLVV--DGGDGSNEEGLKVER
XP_016488923.1            KSGN-FLPWRE-KSKYKQEPVLVVADRGRTEVASEDG-FYLVV--DGGNGSNEEGLKVER
XP_004249913.1            KNGK-LLPWKE-KRKYKEEPVLVVADRGRKEVVVDDG-FYLVLS--GGNGSGDEGLKVER
KAH0714466.1              KSGK-LLPWKE-KRKYKEEPVLVVADRGRKEVVVDDG-FYLVLS--GGNGSGDEGLMVER
KAH0711684.1              KSGK-LLPWKE-KRKYKEEPVLVVADRGRKEVVVDDG-FYLVLS--GGNGSGDEGLMVEK
XP_006350959.1            KSGK-LLPWKE-KRKYKEEPVLVVADRGRKEVVVDDG-FYLVLS--GGNGSGDEGLMVEK
KAG4906474.1              QEHQ-------------------SGVHESRERVGKDA-----------------------
EFH61612.1                --------------------------KPLNHLIYDEG-LIISTC----------GMKLDR
KAG5054963.1              -----LEPLIK----ARSERSL-----TRQEGKQHIG-VIQFND---------IPISIAS
KAG5126716.1              ------------------------------------------------------------
KAH1203488.1              -----------------------------------------------------GCLHLFP
KAH1203487.1              EDCK-LKLWSI------KSGELLFEDKFSDSVISIVC-YKTYGH----------SFKAEE
XP_020878074.1            SDDREVLPWNG-----KEEAIMVVIDREKKTVEADNGYYYLVVA--------EGGMKLDR
sp|Q9SR19|RAF2_ARATH      RDDRKVLPWDG-----KEEPLLVVADRVRNVVEADDG-YYLVVA--------ENGLKLEK
XP_002882362.1            RDDRKVLPCDG-----KEEPLLVVTDRVRNFVEADDGYFLVVAE---------NGLKLEK
KAG5031773.1              -----------------------------------------------------GGSKFGG
KAG5045990.1              -----------------------------------------------------GGSKFGG
CAN61036.1                GDAR-ALPWRV-NRWYKEEAILVVANRGAKEVVADAG-FYLVAV-SSDNGSAGGELKVER
XP_002268548.1            GDAR-ALPWRV-NRWYKEEAILVVANRGAKEVVADAG-FYLVAV-SSDNGSAGGELKVER
RVW88115.1                GDAR-ALPWRV-NRWYKEEAILVVANRGAKEVVADAG-FYLVAV-SSDNGSAGGELKVER
XP_011465980.1            SDAR-VLPWKV-NRWYKEEPILVVADRSKKEVEADDG-FYLAAV-DGEG----LGFKVER
MBA0602665.1              SDAR-VIQWKS-NRWYKEEAILVVTDRNRKEVEVDAA-FYLAMV-DG------GGLKVDT
KJB80888.1                SDAR-VIQWKS-NRWYKEEAILVVTDRNRKEVEVDAA-FYLAMV-DG------GGLKVDT
XP_012463925.1            SDAR-VIQWKS-NRWYKEEAILVVTDRNRKEVEVDAA-FYLAMV-DG------GGLKVDT
EOY10970.1                GDAR-GLPWKA-NRWYKEEPILVVADRSRKEVEFDDG-FYLVTV-DS------GELKVDR
XP_007030468.2            GDAR-GLPWKA-NRWYKEEPILVVADRSRKEVEFDDG-FYLVTV-DS------GELKVDR
XP_021888657.1            GDAR-ALPWKT-KRWYKEEPVLVVADRGRKEVKADDG-FYLVNVADDNG----AGLKIER
XP_002319651.1            PDAR-VLPWKA-NRWYKEESILVVADRGSKEVKADDG-FYLVTL-DGAG----GDFKVER
XP_021624035.1            ADAR-ALPWKA-NRWYKEEAILVVADRGRKEVNVDSG-FYLMAV-ADNGDGRSGALKVER
XP_002521962.1            PDAR-ALPWKV-NRWYKEEAILVVADRGSKEVNANDG-FYLVAV-DGSGDGRSGGLEVER
XP_004142574.1            EDAR-VLPWRV-NRWYKEEPILVVADRSRREVVAGDG-FYLMGGGDGG-----GDLKVER
XP_004495565.1            IDAR-VLPWKA-NKWYKEEPILVVADRSKREVENDDG-FYLVKV-DGDE----LGLKVQR
XP_003590938.1            LDAR-VLPWKANNRWCKEEPILVVADRSKREVENDDG-FYLVKD-DGND----VGLKVQR
AFK41237.1                LDAR-VLPWKANNRWCKEEPILVVADRSKREVENDDG-FYLVKD-DGND----VGLKVQR
XP_007144004.1            PDAR-VLPWKA-NRWYKEEAVLVVADRSKREVGADDG-FYLVNG-YGDD----GGLKVER
AGV54807.1                PDAR-VLPWKA-NRWYKEEAVLVVADRSKREVGADDG-FYLVNG-YGDD----GGLKVER
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              PDAR-VLPWKV-NRWYKEEPILVVADRSKKEVGADDG-FYLVNA-DG------EGLKVER
KAG5152164.1              PDAR-VLPWKV-NRWYKEEPILVVADRSKKEVGADDG-FYLVNA-DG------EGLKVER
KAG4997621.1              PDAR-VLPWKV-NRWYKEEPILVVADRSKKEVGADDG-FYLVNA-DG------EGLKVER
XP_003536143.1            PDAR-VLPWKV-NRWYKEEPILVVADRSKKEVGADDG-FYLVNA-DG------EGLKVER
KAH1191965.1              PDAR-VLPWKV-NRWYKEEPILVVANRSNREVGADHG-FYLVNS-DA------EGLKVQR
KAG4908494.1              PDAR-VLPWKV-NRWYKEEPILVVANRSNREVGADHG-FYLVNS-DA------EGLKVQR
KAG5075806.1              PDAR-VLPWKV-NRWYKEEPILVVANRSNREVGADHG-FYLVNS-DA------EGLKVQR
KAG4919720.1              PDAR-VLPWKV-NRWYKEEPILVVANRSNREVGADHG-FYLVNS-DA------EGLKVQR
KAG4395437.1              PDAR-VLPWKV-NRWYKEEPILVVANRSNREVGADHG-FYLVNS-DA------EGLKVQR
KRH13534.1                VHSP-NEQQQATQKGYSSLLSFTVNDMNNTVTKL----MALGAELDGPIK---YEVHGKG
XP_006598154.1            VHSP-NEQQQATQKGYSSLLSFTVNDMNNTVTKL----MALGAELD-------GPIKYEV
XP_040865419.1            VHSP-NEQQQATQKGYSSLLSFTVNDMNNTVTKL----MALGAELD-------GPIKYEV
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ---------------------RTTK-----------------------------------
XP_003573987.1            GNKLLEEGIITA-AAEVVTVVRPPK-DEED------------------------------
XP_044969817.1            GNKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
BAJ84883.1                GNKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
XP_044449078.1            GKKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
XP_044322972.1            GKKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
XP_044395281.1            GKKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
KAF6988857.1              GKKLLEEGISQA-AAEVVTVVRPPK-DEED------------------------------
BAC99676.1                GRKLGAEGVGEA-AAKVLIVVRPPK-DEDDRHNQCPQPSARSRSRLRSPSRAPSRSPAAA
EAY78710.1                GRKLAAEGVGEA-AAEVLVVVRPPR-DEDD------------------------------
XP_015614647.1            GRKLAAEGVGEA-AAEVLVVVRPPR-DEDD------------------------------
KAB8112826.1              GRKLAAEGVGEA-AAEVLVVVRPPR-DEDD------------------------------
XP_004982996.1            GRKLAEQGITVA-AAEVLIVVRPPR-DEDE------------------------------
XP_002448784.1            GKKLAEQGIAAA-AAEVVIVVRPPK-DEDG------------------------------
NP_001140763.1            GKKLAEQGIAAA-AAEVVIVVRPPK-DEDD------------------------------
XP_016475347.1            GSTLKKRGVEQS-LGIVLIVVRPPR-WEDE------------------------------
XP_016488923.1            GSTLKKRGVEQS-LGIVLIVVRPPKWENED------------------------------
XP_004249913.1            GLNLKEMGVEMS-LGMVLLVVRPPR-WEDE------------------------------
KAH0714466.1              GLTLKEMGVEKS-LGMVLLVVRPPR-WEDE------------------------------
KAH0711684.1              GLTLKEMGVEKS-LGMVLLVVRPPR-WEDE------------------------------
XP_006350959.1            GLTLKEMGVEKS-LGMVLLVVRPPRWEDEE------------------------------
KAG4906474.1              -----EKPIKVS-LRCLAYLNKP-------------------------------------
EFH61612.1                GSVLKEKGVNES-LGMVVLVVRPPSDDDDD------------------------------
KAG5054963.1              ASPDNEYRMLPQ-MSSLVCLTKE-------------------------------------
KAG5126716.1              ---LPPLGLMKL-LGSLVILEITRN-KKNQ------------------------------
KAH1203488.1              GLE-------------------SPR-----------------------------------
KAH1203487.1              ENQYKHDSSQGAWLGSLEGLF---------------------------------------
XP_020878074.1            GSVLKEKGVNES-LGMVVLVVRPPR-DEDD------------------------------
sp|Q9SR19|RAF2_ARATH      GSDLKAREVKES-LGMVVLVVRPPR-EDDD------------------------------
XP_002882362.1            GSELKAREVKES-LGMVVLVVRPPR-EDDE------------------------------
KAG5031773.1              GVA----GLRDG------------------------------------------------
KAG5045990.1              G----VAGLRDG------------------------------------------------
CAN61036.1                GSALKERGVKES-LGTVVLVVRPPR-EETD------------------------------
XP_002268548.1            GSALKERGVKES-LGTVVLVVRPPREETDH------------------------------
RVW88115.1                GSALKERGVKES-LGTVVLVVRPPREETDH------------------------------
XP_011465980.1            GSALKEAGVKES-LGTVVLIVRPPKDDTEN------------------------------
MBA0602665.1              GSALKEMGVKES-LGTVVLVVRPPKEESDD------------------------------
KJB80888.1                GSALKEMGVKES-LGTVVLVVRPPKEESDD------------------------------
XP_012463925.1            GSALKEMGVKES-LGTVVLVVRPPKEESDD------------------------------
EOY10970.1                GSALKETGVKES-LGTVVLVVRPPK-EETD------------------------------
XP_007030468.2            GSALKETGVKES-LGTVVLVVRPPKEETDN------------------------------
XP_021888657.1            GLSLKEAGVEES-LGTVVLVVRPPK-EEID------------------------------
XP_002319651.1            GSALKERNVVEC-LGTVLLVVRPPR-YETD------------------------------
XP_021624035.1            GSELKERGVGES-LGTVVLVVRPPK-EETD------------------------------
XP_002521962.1            GSILKERGVEES-LGTVVLVVRPPK-EQTD------------------------------
XP_004142574.1            GNALMEMGVKES-LGTVLLVVRPPRETEDD------------------------------
XP_004495565.1            GLALKEMGVGEC-LGNVVLVVRPPR-EDND------------------------------
XP_003590938.1            GSILKEMGVNEC-LGNVVIVVRPPT-ENDG------------------------------
AFK41237.1                GSILKEMGVNEC-LGNVVIVVRPPT-ENDG------------------------------
XP_007144004.1            GLTLKEKGFTQS-LGTVLLVVRPPK-DENE------------------------------
AGV54807.1                GLTLKEKGFTQS-LGTVLLVVRPPKDENED------------------------------
XP_025980010.1            ------------------------------------------------------------
KAG5004370.1              GSGLKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG5152164.1              GSGLKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG4997621.1              GSGLKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
XP_003536143.1            GSGLKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAH1191965.1              GFALKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG4908494.1              GFALKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG5075806.1              GFALKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG4919720.1              GFALKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KAG4395437.1              GFALKEKGFTQS-LGTVLLVVRPPK-EEND------------------------------
KRH13534.1                EDLLRESGIPYA-------IVRPCALTEEP------------------------------
XP_006598154.1            HGKVAAMRCIDG----HVLGLYEPV-----------------------------------
XP_040865419.1            HGKVAAMRCIDG---HVLGLYEPVA-----------------------------------
KAG4996767.1              ------------------------------------------------------------
KAG5003541.1              ------------------------------------------------------------
                                                                                      

KAG5148490.1              ---------------------------
XP_003573987.1            --------------IIVGDEWD-----
XP_044969817.1            --------------IIVGDEWD-----
BAJ84883.1                --------------IIVGDEWD-----
XP_044449078.1            --------------IIVGDEWD-----
XP_044322972.1            --------------IIVGDEWD-----
XP_044395281.1            --------------IIVGDEWD-----
KAF6988857.1              --------------IIVGDEWD-----
BAC99676.1                RWLAYGEGENAREREKGEEEKEGREYI
EAY78710.1                --------------MISDDEWD-----
XP_015614647.1            --------------MISDDEWD-----
KAB8112826.1              --------------MISDDEWD-----
XP_004982996.1            --------------MISDEEWD-----
XP_002448784.1            --------------MISDEEWD-----
NP_001140763.1            --------------MVSDEEWD-----
XP_016475347.1            ------------E-QLGEEDWD-----
XP_016488923.1            --------------QLGEEDWD-----
XP_004249913.1            ------------DQQI-DED-------
KAH0714466.1              ------------E-QLIDED-------
KAH0711684.1              ------------E-QLIDED-------
XP_006350959.1            --------------QLIDED-------
KAG4906474.1              ---------------------------
EFH61612.1                ------------DWQINDEDWD-----
KAG5054963.1              ---------------------------
KAG5126716.1              --------------HLENKSR------
KAH1203488.1              ---------------------------
KAH1203487.1              --------------YMC---WL-----
XP_020878074.1            ------------DWQINDEDWD-----
sp|Q9SR19|RAF2_ARATH      ------------DWQTSHQNWD-----
XP_002882362.1            ------------DWQTSHQNWD-----
KAG5031773.1              ---------------------------
KAG5045990.1              ---------------------------
CAN61036.1                ------------H-ELRDEDWE-----
XP_002268548.1            --------------ELRDEDWE-----
RVW88115.1                --------------ELRDEDWE-----
XP_011465980.1            --------------ELAEEDWE-----
MBA0602665.1              --------------QLSDEDWE-----
KJB80888.1                --------------QLSDEDWE-----
XP_012463925.1            --------------QLSDEDWE-----
EOY10970.1                ------------N-QLSDEDWE-----
XP_007030468.2            --------------QLSDEDWE-----
XP_021888657.1            ------------D-QLSDEDWE-----
XP_002319651.1            ------------D-QLSDEDWE-----
XP_021624035.1            ------------D-QLNDEDWE-----
XP_002521962.1            --------------QLSDENWE-----
XP_004142574.1            --------------QLSDEDWD-----
XP_004495565.1            ------------D-QLSEEDWD-----
XP_003590938.1            ------------D-MLSEEDWD-----
AFK41237.1                ------------D-MLSEEDWD-----
XP_007144004.1            ------------D-QLTDEDWE-----
AGV54807.1                --------------QLTDEDWE-----
XP_025980010.1            ---------------------------
KAG5004370.1              --------------ELSDEDWE-----
KAG5152164.1              --------------ELSDEDWE-----
KAG4997621.1              --------------ELSDEDWE-----
XP_003536143.1            --------------ELSDEDWE-----
KAH1191965.1              --------------ELSDEDWE-----
KAG4908494.1              --------------ELSDEDWE-----
KAG5075806.1              --------------ELSDEDWE-----
KAG4919720.1              --------------ELSDEDWE-----
KAG4395437.1              --------------ELSDEDWE-----
KRH13534.1                -----------AGANLILDQGDNITVL
XP_006598154.1            ---------------------------
XP_040865419.1            --------------RIYLEKVAFPMQS
KAG4996767.1              ---------------------------
KAG5003541.1              ---------------------------
                                                     
